### ISSUE TITLE
<sourceEntry>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#108]
## Source Entry
- remove element from EAC-CPF and replace with `<reference>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
Proposal to deprecate or remove <sourceEntry> and use <citation> instead #139 

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@script` - Optional

## Context
A textual identification, such as a title, for a particular source of evidence used to establish the description of the CPF entity in the EAC-CPF instance. 

**May contain**: [text]
**May occur within**: `<source>`
**Attributes:** `@scriptCode`, `@transliteration`, `@xml:id`, `@xml:lang` - all optional
**Availability:** Optional, Repeatable

## Solution documentation
- remove from Tag Library

**Comment by kerstarno** [comment]
Schema test feedback - tested `<sourceEntry>` as this is still available in the schemas (RNG and XSD) in the "development" branch; PENDING decision as to whether this should be replaced by `<reference>`, see also #139, for which there is a variation of the schemas, both RNG and XSD, in the "issue 107" branch (https://github.com/SAA-SDT/eac-cpf-schema/tree/issue/107/xml-schemas/eac-cpf)

Tested against the updated set of attributes, which should be:
- `@audience` - optional (values limited to: external, internal)
- `@id` - optional
- `@languageOfElement` - optional
- `@scriptOfElement` - optional
- `@vocabularySource` - optional
- `@vocabularySourceURI` - optional
- `@valueURI` - optional 
- `@transliteration` should NOT be available anymore as it was decided to remove the attribute and to indicate the transliteration scheme in `<conventionDeclaration>`, which bears the question if `<sourceEntry>` - provided it would be kept - needs to allow for `@conventionDeclarationReference` (note: there already is an exception to the rule of not having the assertion attributes within `<control>` as `<term>` does allow for these attributes as well due to being used in `<control>` and in `<cpfDescription>`

Test result (for both, RNG and XSD):
- `<sourceEntry>` is required and cannot be repeated
- `<sourceEntry>` can have text
- `<sourceEntry>` allows for the optional attributes `@audience`, `@id`, `@languageOfElement`, `@scriptOfElement`, `@vocabularySource`, `@vocabularySourceURI`, `@valueURI`, as well as for the inclusion of several attributes from another namespace (tried with "show" and "actuate" from XLink)

Test successful.

**Comment by kerstarno** [comment]
As a note after having retested #107 - `<sourceEntry>` has been replaced with `<reference>` as the required (and repeatable) sub-element of `<source>`, i.e. `<sourceEntry>` is not available anymore in EAC-CPF 2.0.
