### ISSUE TITLE
<descriptiveNote>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#109]
## Descriptive Note
- add **attributes:**
`@audience`
`@conventationDeclarationReference`
`@maintenanceEventReference`
`@scriptOfElement`
`@sourceReference`
- keep name and scope

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@script` - Optional

**Additional parent elements in EAD3**
`<dao>,` `<daoset>`, `<langmaterial>`, `<languageset>`, `<physdescstructured>`, `<relation>`

**Additional parent elements in EAC-CPF**
`<cpfRelation>`, `<existDates>`, `<function>`, `<functionRelation>`, `<functions>`, `<identity>`, `<languageUsed>`, `<languagesUsed>`, `<legalStatus>`, `<legalStatuses>`, `<localDescription>`, `<localDescriptions>`, `<mandate>`, `<mandates>`, `<occupation>`, `<occupations>`, `<place>`, `<places>`, `<resourceRelation>`, `<rightsDeclaration>`, `<setComponent>`, `<source>`

## Context
A generic element that provides additional information and specifications, in textual form, concerning the descriptive element in which it is contained.

**May contain**: `<p>`
**May occur within**: `<conventionDeclaration>`, `<cpfRelation>`, `<existDates>`, `<function>`, `<functionRelation>`, `<functions>`, `<identity>`, `<languageDeclaration>`, `<languageUsed>`, 
`<languagesUsed>`, `<legalStatus>`, `<legalStatuses>`, `<localDescription>`, `<localDescriptions>`, `<localTypeDeclaration>`, `<maintenanceAgency>`, `<mandate>`, `<mandates>`, `<occupation>`, `<occupations>`, `<place>`, `<places>`, `<resourceRelation>`, `<rightsDeclaration>`, `<setComponent>`, `<source>`
**Attributes:** `@xml:id`, `@xml:lang` - all optional
**Availability:** Optional, Non-repeatable

## Solution documentation

**May contain**:  `<p>` (1..n)
**May occur within**: `<conventionDeclaration>`, `<existDates>`, `<function>`, `<functions>`, `<identity>`, `<languageDeclaration>`, `<languageUsed>`, `<languagesUsed>`, `<legalStatus>`, `<legalStatuses>`, `<localDescription>`, `<localDescriptions>`, `<localTypeDeclaration>`, `<maintenanceAgency>`, `<mandate>`, `<mandates>`, `<occupation>`, `<occupations>`, `<otherEntityType>`, `<otherEntityTypes`, `<place>`, `<places>`, `<relation>`, `<relations>`, `<rightsDeclaration>`, `<rightsDeclarations>`, `<source>`,  `<sources>`
**Attributes:** 
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional

**Availability:** Optional, not repeatable

## Encoding example
 ```
<descriptiveNote audience="external" conventionDeclarationReference="conventiondeclaration1" id="descriptivenote1" languageOfElement="en" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1">
   <p>A generic element that provides additional information and specifications, in textual form, concerning the descriptive element in which it is contained.</p>
</descriptiveNote>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An element used to provide general descriptive information related to its parent element.
**May contain:** p (1..n)
**May occur within:** conventionDeclaration, existDates, function, functions, identity, languageDeclaration, languageUsed, languagesUsed, legalStatus, legalStatuses, localDescription, localDescriptions, localTypeDeclaration, maintenanceAgency, mandate, mandates, occupation, occupations, otherEntityType, otherEntityTypes, place, places, relation, relations, rightsDeclaration, source, sources
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:**
`<descriptiveNote>` provides additional descriptive information about the element in which it is contained. `<descriptiveNote>` must contain one or more `<p>` elements.
**Availability:** Optional, not repeatable

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `<descriptiveNote>` is an optional sub-element of the declaration elements (`<conventionDeclaration>`, `<languageDeclaration>`, `<localTypeDeclaration>`, `<rightsDeclaration>`), of the `<control>` sub-element `<maintenanceAgency>`, `<source>`,  `<sources>`, of `<identity>`, `<otherEntityType>`, and `<otherEntityTypes`>, of `<existDates>`, of the singular elements (`<function>`, `<languageUsed>`, `<legalStatus>`, `<localDescription>`, `<mandate>`, `<occupation>`, `<place>`), of the plural elements (`<functions>`, `<languagesUsed>`, `<legalStatuses>`, `<localDescriptions>`, `<mandates>`, `<occupations>`, `<places>`), of `<relation>` and `<relations>`.
- `<descriptiveNote>` requires the sub-element `<p>`, which can be repeated
- `<descriptiveNote>` allows for the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, and `@sourceReference`  
- `<descriptiveNote>` also allows for optional attributes from other namespaces (tested with XLink)

The above applies to RNG and XSD schemas alike.

The element is ready.

@SJagodzinski and @fordmadox - there also is a `<descriptiveNote>` with `<setComponent>` at the moment, so presumably pending the general decision on `<alternativeSet>`. 

I would hence consider this issue here as done from the schema perspective and would suggest confirming the potential addition of `<setComponent>` as another possible parent element of `<descriptiveNote>` in #223. @ailie-s depending on the solution to `<setComponent>`, i.e. when `<setComponent>` is kept as is, the TL draft for `<descriptiveNote>` would then need to be updated.

**Comment by SJagodzinski** [comment]
In case we keep `<alternativeSet>`, I think we won't change the current specification but changing attributes due to our decisions and removing `<objectXMLWrap>`.
