### ISSUE TITLE
<entityId>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#115]
## Entity Identifier
- **rename** to `<identityId>` and define as identity identifier
- review **attributes:**
a) review if new attribute `@status` is suitable
- add new optional attribute:
 `@audience`
`@conventationDeclarationReference`
 `@languageOfElement`
`@localTypeDeclarationReference`
`@maintenanceEventReference`
 `@scriptOfElement`
 `@sourceReference`
`@valueURI`
`@vocabularySource`
`@vocabularySourceURI`
- specify **Best Practise Guide** for usage and examples of different descriptions of the same identity
- **review parent elements**: also suitable for `<cpfRelation>` 

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
`<entityId>:` definition #55 
`<otherRecordId>:` definition #54 

## EAD3 Reconciliation
EAC-CPF specific element

## Context
Any formal identifier used to designate the entity being described.

**May contain**: [text]
**May occur within**: `<identity>`
**Attributes:** `@localType`, `@xml:id` - all optional
**Availability:** Optional, Repeatable

## Solution documentation: 
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed

**May contain**: [text]
**May occur within**: list to follow
**Attributes:** 
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional

**Availability:** Optional, Repeatable

- New or other example needed
- Topic for Best Practise Guide: 
> Example of different descriptions of the same identity should be given in `<cpfRelation>` not in `<entityId>.`

## Example encoding
```
<identity>
 <identityId audience="external" conventionDeclarationReference="conventiondeclaration1" id="identityId1" languageOfElement="en" localType="localtype" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1" vocabularySource="identityIdVocabulary" vocabularySourceURI="http://identityIdVocabularyURI" valueURI="https://identyIdURI">identity identifier</identityId>
 <entityType value="family"/>
 <nameEntrySet>
  [...]
 </nameEntrySet>
 <descriptiveNote>
  <p></p>
 </descriptiveNote>
</identity>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**`<identityID>`   Identity Identifier**
**Summary:** An optional child element of `<identity>` used to record any identifier associated with the CPF entity being described
**May contain:** [text]
**May occur within:** identity
**Attributes:**
`@audience `- optional (values limited to: external, internal)
`@conventationDeclarationReference `- optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference `- optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI `- optional
**Description and Usage:**
`<identityId>` may be used to record any identifier associated with the CPF entity being described in the EAC-CPF instance. Identifiers such as legal identifiers, typically assigned by an authoritative agency, may be recorded in this element.
Do not confuse with `<recordId>` within `<control>`, which refers to an identifier for the EAC-CPF instance rather than the entity it describes.
**Availability:** Optional, Repeatable

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing: 

- `<identity>` does not include a sub-element call `<entityId>` anymore
- instead, `<identity>` allows for the optional sub-element `<identityId>`
- `<identityId>` can be repeated
- `<identityId>` can contain text
- `<identityId>` does not have sub-elements of its own
-  `<identityId>` allows for the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, `@localType`, `@localTypeDeclarationReference`, `@valueURI`, `@vocabularySource`, and `@vocabularySourceURI`
- `<identityId>` also allows for optional attributes from other namespaces (tested with XLink)

The above applies to both schemas, RNG and XSD. 

The element is ready. 

@ailie-s - the TL draft is currently missing `@target`.
