### ISSUE TITLE
@instanceUrl

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#130]
## Instance URL
The idea to add the optional attribute `@instanceUrl` with data type any URI to `<recordId>` and to follow EAD for alignment was rejected. Use `<representation>` with `@href` link and explain this approach in the documentation/best practices. guidelines.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[20200128_SharedSchemaOverview](https://docs.google.com/document/d/1o9mtdzEzNTize7EGvEfKCsFR4ZY_OCVIXZdLDzOJnrY/edit)

## EAD3 Reconciliation
Decision from EAC-EAD-Schema joint meeting, 28 Jan 2020, due to alignment of in both standards.

**Summary:**
The URL for the EAD instance itself (as opposed to HTML or other derivatives, which may be captured in `<representation>` elements). Available on `<recordid>.`

**Data Type:** anyURI

## Context
EAD3 specific attribute.

## Solution documentation
no added

**Comment by fordmadox** [comment]
Adding to the draft schema, but I think that we might want to discuss this attribute again.

Given that ```@instanceurl``` is only used in one location in EAD3; and that the examples that I've seen in the real world don't line up with the TL definition; and given that I don't know of other XML schemas that attempt to provide a canonical URL for the XML file within the XML file itself:  I wonder if this attribute is needed in either schema?  If kept, then I think that additional documentation should be provided.  

Also, not sure how/if other XML schemas handle this, but in HTML you can use a link tag like so:

``` 
<link rel="canonical" href="https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN" />
```

So, in EAD3's case, I like that this attribute is available in control, but I'm not sure if ```recordid``` is the best place to use it (nor if it's really needed).  The ```recordid``` element stores the primary _identifier_ for the record, so having an attribute on it that provides a link to the entire record itself doesn't seem entirely right to me (as the url is not qualifying the ID).  Something like html/head/link, however, is more clear, to me at least, since you are providing a link (possibly back, possibly self-referencing ) to the canonical version of the file itself.

**Comment by kerstarno** [comment]
Not sure, but would people use `@instanceURL` e.g. to enable downloads of their online finding aids or authority records in XML format? Or to maybe provide a link to the original XML when the EAS instances are shared with aggregators and enriched in that context? I know that we are using the attribute `@url` in that way in Archives Portal Europe, although we are rather pointing to the original HTML representation than to the original XML (seeing that we are using EAD 2002, which doesn't have such distinction).

Should we consider taking an alternative approach via a linking element, may be we could (re)consider incorporating `@instanceURL` in `<representation>` (#140), which already comes with the set of linking attributes, i.e. using a simple `@href` instead of `@instanceURL`? And if we'd consider that, might it be useful to consider introducing the terminology of "Instantiation" (instead of `<representation>`) picking up on RiC?

**Comment by fordmadox** [comment]
I think that would make a lot more sense than having an attribute named instanceURL on an element named recordid.  I've got the "EAD3 way of doing things" set up in a draft version of the schema, but I think it would be a good idea to try out this suggestion in a different branch.

**Comment by SJagodzinski** [comment]
Outcome EAC-CPF September 2020 meeting:

Agree to remove @instanceURL and not follow EAD; agree to move toward using `<representation>` with href link. 
Explain this approach in the documentation/best practices guidelines.

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** The URL for the EAC-CPF instance itself (as opposed to HTML or other derivatives). Available on `<recordId>`.
**Data type:** anyURI

**Comment by SJagodzinski** [comment]
@ailie-s : Sorry, my fault. `@instanceURL` will be omitted resp. not intruduces, cf https://github.com/SAA-SDT/eac-cpf-schema/issues/130#issuecomment-696888611.

**Comment by kerstarno** [comment]
I think, this still needs to go through schema testing, too, even if only to confirm that the attribute is not in the schema anymore. Will do that check later on today or early tomorrow.

**Comment by fordmadox** [comment]
I still have instanceURL on recordId, but I'll update that in just a bit.

**Comment by kerstarno** [comment]
Just to confirm for schema testing, that `@instanceURL` has been removed (again) from RNG and XSD schemas.
