### ISSUE TITLE
<part>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#133]
## Part
- keep name and scope
- add optional attributes
`@audience`
`@conventationDeclarationReference`
`@localTypeDeclarationReference`
`@maintenanceEventReference` 
`@scriptOfElement`
`@sourceReference`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender`
`@audience`
`@encodinganalog`
`@identifier`
`@rules`
`@script`
`@source`

**May contain**: [text], `<abbr>`, `<date>` , `<emph>` , `<expan>` , `<foreign>` , `<lb>` , `<ptr>` , `<ref>`
**May occur within**: `<corpname>`, `<famname>`, `<function>`, `<genreform>`, `<geogname>` ,`<name>`,`<occupation>`, `<persname>`, `<subject>`, `<title>`
**Availability:** Required, repeatable.

## Context
`<part>` is used to distinguish components of the name of the CPF entity's name within `<nameEntry>.`

**May contain**: [text]
**May occur within**: `<nameEntry>`
**Attributes:** `@localType`, `@xml:id`, `@xml:lang` - all optional
**Availability:** Mandatory, Repeatable

## Solution documentation
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain**: [text]
**May occur within**: `<nameEntry>`, `<targetEntity>`
**Attributes:** 
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional

**Availability:** Required, repeatable

## Example encoding
```
<nameEntry>
 <part audience="external" conventionDeclarationReference="conventiondeclaration1" id="part1" languageOfElement="en" localType="localPart" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1">name part</part>
 <useDates></useDates>
</nameEntry>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A required and repeatable child of `<nameEntry>` used to distinguish components of the name of the CPF entity's name.
**May contain:** [text]
**May occur within:** nameEntry
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
**Description and Usage:** Within `<nameEntry>` each of the component part of a name, such as forename, surname or honorific title, may be recorded in a separate `<part>` element. `<part>` may also contain the full name of the entity when it is not possible to distinguish the different component parts of the name.
**Attribute Usage:** The designation of the information contained in the `<part>` can be specified by the attribute `@localType`.
**Availability:** Required, repeatable

**Comment by karinbredenberg** [comment]
Test of element part:
May occur within: nameEntry 1..n **Ok in both schemas**
May contain: [text] **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@conventationDeclarationReference - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@localType - optional **Missing in both schemas**
@localTypeDeclarationReference - optional **Missing in both schemas**
@maintenanceEventReference - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@sourceReference - optional **Ok in both schemas**

**Result**: Element needs to be updated with both the localType attributes.

**Comment by karinbredenberg** [comment]
Retested: 
@localType - optional **OK in both schemas**
@localTypeDeclarationReference - optional **Ok in both schemas**

**Result**: Element ready.

**Comment by ailie-s** [comment]
Updated Tag Library Text:

**Summary:** A required and repeatable child of `<nameEntry>` and <`targetEntity>` used to distinguish components of the name of the CPF entity's name, or the name of a related entity.
**May contain:** [text]
**May occur within:** nameEntry, targetEntity
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:** Within `<nameEntry>` each of the component part of a name, such as forename, surname or honorific title, may be recorded in a separate `<part>` element. `<part>` may also contain the full name of the entity when it is not possible to distinguish the different component parts of the name.
Within `<targetEntity>` the name or term for the related entity is encoded within `<part>` elements.
**Attribute Usage:** The designation of the information contained in the `<part>` can be specified by the attribute `@localType`.
**Availability:** Required, repeatable

**Comment by kerstarno** [comment]
@SJagodzinski and @fordmadox for information:

The most recent EAC Team meeting discussed the question of potentially requiring content for those elements that are currently mandatory for a minimum EAC instance. `<part>` as sub-element of `<nameEntry>` is one of these. The Schema Team followed up on this during their meeting today and suggest to keep `<part>` as mandatory and to require it to at least have 1 character. This is based on the assumption, that - when describing a CPF entity - one will have some kind of name.

Schema Team also discussed the option of allowing `@valueURI` with `<nameEntry>` to be used instead of content in `<part>`, but we felt that there are too many if-s and but-s with regard to that URI actually providing an option to extract a label - e.g. when servers are temporarily not accessible or when URI-s change and no referencing is implemented. 

For background see also: https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/schemas-subteam/working-documents/20210108_ContentRequirement_MandatoryElements.pdf

**Comment by fordmadox** [comment]
Just updated the schema so that this approach can be tested (see https://github.com/SAA-SDT/eac-cpf-schema/commit/fff58de08bc13584ed7f493d46561e746961086e).  I think this is a good approach (since if valueURI is used, then a label should be able to be added to 'part', although in that case it might be useful to have lastDateTimeVerified, which you cannot do currently).  

Not sure if this restriction is perfect, though, yet.  Right now, the restriction is that at least one non-whitespace character must be present.  Is that fair?  I think it is, unless we want to introduce xml:space, otherwise a single whitespace character could still result in an empty element, which is what we had prior (so, right back to just "text" :smile: )

**Comment by kerstarno** [comment]
Pending final confirmation.

**Comment by SJagodzinski** [comment]
> The most recent EAC Team meeting discussed the question of potentially requiring content for those elements that are currently mandatory for a minimum EAC instance. `<part>` as sub-element of `<nameEntry>` is one of these. The Schema Team followed up on this during their meeting today and suggest to keep `<part>` as mandatory and to require it to at least have 1 character. This is based on the assumption, that - when describing a CPF entity - one will have some kind of name.

I agree.

**Comment by kerstarno** [comment]
With the confirmation of requiring at least one non-white space character within `<part>`, the element is ready.
