### ISSUE TITLE
<otherEntityType>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#142]
## Other Entity Types
- **add as new** mandatory and repeatable child **element** to `<otherEntityTypes>`
- add attributes:
`@audience`
`@conventationDeclarationReference`
`@id`
`@languageOfElement`
`@localType`
`@localTypeDeclarationReference`
`@maintenanceEventReference`
`@scriptOfElement`
`@sourceReference`
`@valueURI`
`@vocabularySource`
`@vocabularySourceURI`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
Add new content for `<entityType>` #44

## EAD3 Reconciliation
EAC-CPF specific element

## Context
new element

## Solution documentation: 
_Summary_, _Description and Usage_ and _Attribute usage_ needed

May contain: `<date>` or `<dateSet>` or `<dateRange>`, `<descriptiveNote>`, `<placeEntry>`, `<term>`
May occur within: `<otherEntityTypes>`
Attributes:
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
Availability: Required, Repeatable

- Example needed
- Topic for Best Practise Guide

## Example ecoding
```
<otherEntityTypes>
 <otherEntityType audience="external" conventionDeclarationReference="conventiondeclaration1" id="otherEntityType1" languageOfElement="en" localType="localentitytype" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1" valueURI="http://valueURI" vocabularySource="source" vocabularySourceURI="http://sourceURI">
  <term>term for other entity type</term>
  <placeEntry>place entry for other entity type</placeEntry>
  <date>date for other entity type</date>
  <reference>citation for other entity type</reference>
  <descriptiveNote>
   <p>descriptive note for other entity type</p>
  </descriptiveNote>
  </otherEntityType>
  <otherEntityType>
  <term>term for other entity type</term>
 [...]
 </otherEntityType>
  [...]
</otherEntityTypes>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A required and repeatable child element of `<otherEntityTypes>` used to encode additional or alternative entity types.
**May contain:** date or dateRange or dateSet (0..1), descriptiveNote (0..1), placeName (0..n), term (1..n)
**May occur within:** otherEntityTypes
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Description and Usage:** 
`<otherEntityType>` is a required child element of `<otherEntityTypes>` used to encode any additional or alternative entity types used for the CPF instance in addition to the required` <entityType>` element with values of corporateBody, person or family. For example in a local context 'organization' might be used as an entity type instead of 'corporateBody'. `<otherEntityType>` allows 'organization' to be encoded.
`<otherEntityType>` must include one `<term>` element containing the term for the other entity type. 
Each CPF instance may include more than one `<otherEntityType>` elements within the `<otherEntityTypes>` wrapper element.
**Availability:** Required, Repeatable

**Comment by karinbredenberg** [comment]
Test of element otherEntityType:
May occur within: otherEntityTypes 1..n **Ok in both schemas**
May contain: date or dateRange or dateSet (0..1),  **Ok in both schemas**
descriptiveNote (0..1),  **Ok in both schemas**
placeEntry (0..n),  **Ok in both schemas with new name placeName**
reference (0..1),  **Ok in both schemas**
term (1..n) **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@conventationDeclarationReference - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@localType - optional **Ok in both schemas**
@localTypeDeclarationReference - optional **Ok in both schemas**
@maintenanceEventReference - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@sourceReference - optional **Ok in both schemas**
@valueURI - optional **Ok in both schemas**
@vocabularySource - optional **Ok in both schemas**
@vocabularySourceURI - optional **Ok in both schemas**

**Result**: Element ready. @target has been added. @ailie-s just a reminder to you to change the name of element placeEntry to placeName.

**Comment by fordmadox** [comment]
@karinbredenberg: I added the "tested" label and assigned the TL milestone.  Just an FYI in case there was anything else needed for this element in the schemas.

**Comment by fordmadox** [comment]
Just a note that "reference" has currently been removed (during the automated build process) from this element, which has been modeled the same way as the "singular" elements in description.  Does that need to change now? I need to check the minutes from the last EAC meeting, since I am still unclear on the final proposal regarding "reference" from that meeting.

**Comment by kerstarno** [comment]
According to the minutes, only the following elements will have `<reference>`:

"Add `<reference>` to elements with descriptive content and to elements containing the former element `<citation>` [...]: `<abstract>`, `<chronItem>`, `<chronItemSet>`, `<conventionDeclaration>`, `<event>`, `<eventDescription>`, `<item>`, `<localTypeDeclaration>`, `<p>`, `<rightsDeclaration>`, `<source>`."

I.e. no `<reference>` as direct sub-element of the single elements anymore, which will however still have it available via `<descriptiveNote><p><reference>`. I.e. no need to (re-)add it to `<otherEntityType>`.
