### ISSUE TITLE
@valueURI

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#146]
## Value URI

Add optional attribute `@valueURI` with data type anyURI to all elements that could be represented by an URI.

List of elements: `<agencyCode>`, `<agencyName>`, `<agent>`, `<componentEntry>`, `<conventionDeclaration>`, `<event>`, `<function>`, `<identityId>`, `<legalStatus>`, `<localControl>`, `<localDescription>`, `<localTypeDeclaration>`, `<maintenanceAgency>`, `<mandate>`, `<nameEntry>`, `<occupation>`, `<otherAgencyCode>`, `<otherEntityType>`, `<otherRecordId>`, `<place>`, `<placeName>`, `<placeRole>`, `<relationType>`, `<rightsDeclaration>`, `<source>`, `<targetEntity>`, `<targetRole>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Topic_relations_20200327.pdf](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/relations/Topic_relations_20200327.pdf)
Add local identifier attribute #45
[20201002_EAC-CPF_minutes.pdf](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/meeting-minutes/2020/20201002_EAC-CPF_minutes.pdf)

## EAD3 Reconciliation
New attribute

## Context
New attribute in EAS.
MODS: [valueURI](https://www.loc.gov/standards/mods/userguide/attributes.html#valueURI)

## Solution documentation: agreed solution for TL and guidelines
_Summary_, _Description and Usage_ and _Attribute usage_ needed

**Data Type**: anyURI

- New or other example needed
- Topic for Best Practise Guide?

## Example encoding

**Comment by SJagodzinski** [comment]
Proposal for _Summary:_

An URI identifying the resource to be used as the elements value.

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional attribute for including a URI identifying the resource to be used as the element's value.
**Data Type:** anyURI

**Comment by kerstarno** [comment]
Putting this here as a note for now as I came across it by coincidence while testing `<conventionDeclaration>` with `@valueURI`:

- Currently `@valueURI`'s data type is correctly defined as "anyURI", but it also comes with the further restriction of expecting the following pattern: "http[s]?://.*" (which is different to how `@href` is defined).
- This leads to the attribute always expecting the full URL, it would seem.
- So, if one e.g. used `@base="http://d-nb.info/gnd/"` with `<description>` to indicate that all references in that section will point to terms from the GND, one would still have to put in the full link for `@valueURI`, i.e. `@valueURI="http://d-nb.info/gnd/1190671301"`, instead of simply putting `@valueURI="1190671301"`.
- Not sure, if we want to enforce full links for `@valueURI` in all cases?
- Or maybe I've not understood the usage of `@base` correctly?

The same question would apply to `@vocabularySourceURI` (#148).

**Comment by SJagodzinski** [comment]
I agree, that restriction annoying and excludes eg URNs.

**Comment by fordmadox** [comment]
Updating now to relax the URI restriction (which I was going to do anyway, since I expect that there are / will be other protocols other than HTTP for the linked data attributes).

That said, I think we need to do a review of `@base`.  This attribute was previously xml:base, in EAC 1.x, which is defined very specifically (see http://www.w3.org/TR/xmlbase/).  I was assuming that it was now bound to the `@href` attribute only, similarly to HTML base.  However, we now have `@valueURI`, `@vocabularlySourceURI`, and `@href`.  I don't think that "base" can serve as the base URI for all three.   Perhaps coming up with mappings will help here, especially for mapping to other formats, like JSON-LD, RDF/XML, etc.

**Comment by fordmadox** [comment]
Updated here:  https://github.com/SAA-SDT/eac-cpf-schema/commit/7118375b28236fe1fdc0a006a532d614ab0374cf.  Will add a comment on the `@base` issue.  I'm not sure how it can serve the same purpose for all three attributes, but I haven't done any explorations.

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@valueURI` is an optional attribute for the 27 elements listed in the issue description above, i.e. `<agencyCode>`, `<agencyName>`, `<agent>`, `<componentEntry>`, `<conventionDeclaration>`, `<event>`, `<function>`, `<identityId>`, `<legalStatus>`, `<localControl>`, `<localDescription>`, `<localTypeDeclaration>`, `<maintenanceAgency>`, `<mandate>`, `<nameEntry>`, `<occupation>`, `<otherAgencyCode>`, `<otherEntityType>`, `<otherRecordId>`, `<place>`, `<placeName>`, `<placeRole>`, `<relationType>`, `<rightsDeclaration>`, `<source>`, `<targetEntity>`, `<targetRole>`
- Its data type is _anyURI_ (and the initial restriction has been lifted)
- It's always available together with the attributes `@vocabularySource` and `@vocabularySourceURI`

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
