### ISSUE TITLE
<agencyCode>: add attribute @type

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#15]
Add an attribute `@type` to the element `<agencyCode>` within `<maintenanceAgency>`.

## Creator of issue

1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Added `@type` attribute, example values: ISIL (registered); ISIL (compatible); and so on. [used by SNAC, contributed by @dpitti].

## Suggested Solution

EAC-CPF schema is not using the attribute `@type` so far, but the attribute `@localType`. Hence, adding `@localType` could be a solution.

## Context
see  also #14

**Comment by karinbredenberg** [comment]
Align with EAD3.

**Comment by karinbredenberg** [comment]
The type is named localtype in EAD3 so do the same here.

**Comment by SJagodzinski** [comment]
Add an optional attribute `@localType` to the element `<agencyCode>` within `<maintenanceAgency>`.

**Comment by SJagodzinski** [comment]
Results of team discussion:

Using `@localType` restricts the attribute to local, but doesn't general definition. 
Using `@type` would be a better solution, see #14.

Discussion points:

- Distinction between @type and @localtype (there are two different functions here).

- Reconciliation should account for distinctions between definitions and labels. (e.g., @type needs to mean the same thing in both standards, @localtype needs to mean the same thing in both standards, etc.); a discussion for phase 2.

**Comment by rockivist** [comment]
Chiming in here with some perspective from the EAD3 revision process. 

We intentionally removed all instances of the `@type` attribute from EAD because it meant different things in different contexts. Some examples were undefined and others had established value lists. For instances where we felt it necessary to preserve a generic way to subclass an element, we changed `@type` to `@localtype`, following the convention from EAC. Where we kept an attribute with a closed set of subclass values, we prefixed type with the name of the element, e.g. `@unitdatetype` ([https://www.loc.gov/ead/EAD3taglib/index.html#attr-unitdatetype](url)). This added more attributes, but clarified the semantics greatly.

Since there is no `@type` attribute in EAC, I'd argue against introducing it. If for the agencyCode element you want to provide a generic way to subclass the element, add `@localType`, which will be in alignment with EAD. If it is deemed necessary to supply a closed list of values, I'd suggest adding an attribute called '@agencyCodeType' with a few values, including 'ISO15511", "ISIL" and "otherAgencyCodeType" along with a companion `@otherAgencyCodeType` attribute. I think that could be incorporated into EAD without much trouble.

Whatever the group chooses, just don't introduce a generically named `@type` attribute.

**Comment by SJagodzinski** [comment]
### Result of team discussion:
The team agrees with @rockivist.

According to #14 solution, there is no need for a closed list of values. The element `<agencycode>` might contain local identifiers, therefore there is no reason to restrict the values. 

Leaving `<agencycode>` open, as agreed in #14, there is a need for an attribute identifying the data value standard. `@localtype` _is intended to provide a means to narrow the semantics of_ elements (see [tag library](http://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary_EN.html#localType)) and doesn't match the concept here. 

To identify the data value standard a distinct and specific attribute is useful and might be also suitable for other elements. This element would ideally be mandatory in order to avoid meaningless code.

Introducing a new attribute with a wide scope like identifying data value standards seems to be a comprehensive issue, that should be carefully discussed and is scheduled for eac-cpf revision (phase). 
Ergo, both issue #14 and #15 aren't solved with the update and are forwarded to phase 2.

**Comment by kerstarno** [comment]
_From the team discussion on 3 May 2019_

It seems there are two different things that we would want to say about the identifier given in `<agencyCode>`: 
1. Where does this identifier come from? To what standard/code does this identifier comply?
2. Is this identifier officially registered as part of that standard, i.e. in its "system of origin"?

While (1) speaks about "types" of standards/codes, e.g. ISIL, ISO15511, ISNI, some national standard, etc., (2) qualifies the identifier as part of the relevant standard/code with regard to the identifier being official/authoritative/unique, i.e. might be a simple "yes"/"no" or "true"/"false" statement. And while (1) should probably be left as open as possible to allow for local/national "types" of standards/codes, (2) could potentially be restricted to a rather short list of possible values.

Based on this, we could consider suggesting the addition of two attributes: 
- `@...Type`
   Suggestion for values: no pre-defined list of values
   Note: I'd still argue for using `@localType` as EAD3 does, rather than adding a specific 
   `@agencyCodeType`
- `@authorized` 
   Suggestion for values: "true" and "false"
   Note 1: The naming of this attribute would be kind of in line with having an element called 
   `<authorizedForm>` for the name of the entity described.
   Note 2: If agreed, this new attribute should also be added to `<agencycode>` in EAD3.

**Comment by kerstarno** [comment]
_From the team discussion on 3 May 2019_

Two aspects to investigate further:
- How does this question relate to the more general discussion around identifiers?
- Are there any other elements in EAC-CPF and/or EAD3 to encode identifiers, where similar statements (type of identifier, authoritative status of identifier) could be made? If yes, how is this question addressed in the context of those elements?

**Comment by SJagodzinski** [comment]
To qualify the agency code as authorised or offical, the new attribute `@status`, cf. #70, can be used. This attribute is supposed to qualify a name entry as authorised or alternative. 

Restricted values to qualify an agency code are useful and need to be decided. Values true/false are not feasable with `@status`.

**Comment by SJagodzinski** [comment]
EAC-CPF Berlin meeting, 11 March 2020:

Hand a decision over to the Schema team, if `@localType` can be used in <control> elements.

Hand a discussion on reintroducing `@type` over to the Schema team.

**Comment by SJagodzinski** [comment]
TS-EAS meeting, 6 August 2020:

Keep attribute `@localType`. Look over the control area and make sure it’s available where needed, and if adding `@localType` to  declaration elements, a `@[...]Reference` attribute is highly recommended (schematron).
