### ISSUE TITLE
@xml:id

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#150]
## Element Identifier

Replace `@xml:id` with optional attribute `@id` with data type ID. Use `@id` as global attribute in all elements, but the root element `<eac>`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Remove xml ns to align with EAD 3 #27](https://github.com/SAA-SDT/eac-cpf-schema/issues/27)

## EAD3 Reconciliation
Summary:
An identifier that must be unique within the current document and is used to name the element so that it can be referred to, or referenced from, somewhere else. This facilitates building links between the element and other resources. Do not confuse with identifier, which provides a machine-processable identifier for an entity or concept in an external system.

Data Type: ID

## Context
@xml:id XML Identifier  

Summary:
A unique identifier available on most elements that can be used to name specific elements in the EAC-CPF instance.
Description and Usage:
An identifier used to name the element so that it can be referred to, or referenced from, somewhere else. Each xml:id within a document must have a unique value. The xml:id attribute regularizes the naming of the element and thus facilitates building links between it and other resources. For example, the xml:id may be used to uniquely identify two or more <cpfDescription> within <multipleIdentities>. Uniquely identifying or distinguishing two or more <cpfDescription> may be essential or useful in maintenance environments when relating resources, functions, or corporate bodies, persons, or families to one among two or more identities represented in one EAC-CPF instance.

Data Type: NMTOKEN

## Solution documentation: agreed solution for TL and guidelines

**Summary:** An identifier that must be unique within the current document and is used to name the element so that it can be referred to, or referenced from, somewhere else. This facilitates building links between the element and other resources. 

**Data Type**: anyURI

## Example encoding

**Comment by kerstarno** [comment]
@fordmadox - not tested `@id` in itself, but came across the following while testing `<source>`: while the XSD correctly requires each `@id` attribute to have a unique value, the RNG doesn't. I.e. I can have id="s1" with `<sources>` AND with `<source>` without getting a validation error when using the RNG.

**Comment by fordmadox** [comment]
@kerstarno good catch!  this brings this in alignment with EAD3, apparently :smile:.  I'll have to investigate why this is in Relax NG, and how to fix it, but it rings a bell.   

just tested TEI Lite's RNG deliverable, and I get the same results.  e.g., this is valid:

```
<TEI xmlns="http://www.tei-c.org/ns/1.0" xml:id="t1">
    <teiHeader xml:id="t1">
        <fileDesc xml:id="t1">
...
```

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing: 

- `@xml:id` does not exist anymore in the draft schema for EAC-CPF 2.0
- Instead, `@id` is available with all 89 elements of EAC-CPF 2.0
- Its data type is _ID_
- It is always available alongside `@audience`
- It is always available alongside `@target`, with the exception of `<eac>` where `@target` is not available

The above applies to both schemas, RNG and XSD. 

The attribute is ready.

**Comment by kerstarno** [comment]
@fordmadox I've labelled this issue as "Tested" and moved it on to the "Tag Library" stage seeing that the attribute is defined in both schemas as expected. There is, however, still the open question with regard to the RNG schema allowing multiple iterations of the same value for `@id` in different elements.

**Comment by fordmadox** [comment]
@kerstarno :  this turns out to be an intentional design decision in Relax NG.  See https://relaxng.org/jclark/design.html#section:16.  

In EAC 1.x, xml:id was defined with the NCName datatype rather than ID.  That was due to the decision to allow *any* elements in *any* namespace, including the current one, within objectXMLWrap.  In EAC 2.0, the new "id" attribute is defined using the ID attribute, so it is defined now with the appropriate datatype (and aligns with EAD3's definition of "id"). 

That means that the id attribute in EAC 2 behaves the same way right now in EAD3.  However, you can use oXygen, for instance, to turn on testing of ID/IDREF uniqueness if you want (e.g. Options --> Preferences --> XML --> XML Parser --> RELAX NG", and then select the "Check ID/IDREF" option).  

If we want to ensure a consistent behavior when users are using the RNG or XSD, I believe that we will need to embed this Schematron rule directly in the RNG file (and it doesn't look like the EAD3 schematron has a rule for this at all, so the uniqueness is not being checked in that context currently).  Because of that, I wonder if we shouldn't pursue embedding the schematron rules directly in both the RNG and XSD deliverable files, rather than keeping them entirely separate.  But, more to think about with the Schematron approach.

**Comment by kerstarno** [comment]
Perfect. Thanks for the feedback, @fordmadox. Mainly wanted to note it here on GitHub somewhere in case we wanted to address it somehow.
