### ISSUE TITLE
<list>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#171]
## List
- add optional attributes:
`@audience` 
`@conventationDeclarationReference`
`@listType`
`@localTypeDeclarationReference` 
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference` 
`@style`
- add `<list>` as new child element to `<list>`
- add new optional child element `<head>`
- keep name and scope

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender`, `@audience`, `@listtype`, `@mark`, `@numeration`, `@script` - all optional
**May contain**: defitem, head, item, listhead

## Context
**Summary:** A wrapper element to encode a simple list consisting of one or more `<item>` elements.
**May contain**: item
**May occur within**: biogHist, functions, generalContext, legalStatuses, localDescriptions, mandates, occupations, places, structureOrGenealogy
**Attributes:** `@localType`, `@xml:id`, `@xml:lang`
**Availability:** Optional, Repeatable

## Solution documentation: 

**May contain**: `<head>` (0..1), `<item>` (0..n), `<list>` (0..n)
**May occur within**: `<biogHist>`, `<generalContext>`, `<structureOrGenealogy>`
**Attributes:** 
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional  
`@id` - optional  
`@languageOfElement` - optional 
`@listtype` - optional (values limited to: deflist, ordered, unordered)
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@mark` - optional (values limited to: disc, circle, inherit, none, square)
`@maintenanceEventReference` - optional
`@numeration` - optional (values limited to: armenian, decimal, decimal-leading-zero, georgian, inherit, lower-alpha, lower-greek, lower-latin, lower-roman, upper-alpha, upper-latin, upper-roman)
`@scriptOfElement` - optional
`@sourceReference` - optional

**Availability:** Optional, Repeatable

- New or other example needed

## Example encoding
```
<list audience="external" conventionDeclarationReference="cd1" id="l1" languageOfElement="en" listType="ordered" localType="locallist" localTypeDeclarationReference="ltd1" maintenanceEventReference="me1" scriptOfElement="lat" sourceReference="source1" style="list-style-type: decimal" target="element1">
 <item>list item</item>
 </list>                  
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A wrapper element to encode a simple list consisting of one or more `<item>` elements, or a complex list with one or more child `<list>` elements.
**May contain:** head (0..1), item (0..n), list (0..n)
**May occur within:** biogHist, generalContext, structureOrGenealogy
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReferenc`e - optional
`@id` - optional
`@languageOfElement` - optional
`@listType` - optional (values limited to: ordered, unordered)
`@localType` - optional
`@localTypeDeclarationReference `- optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@style` - optional
`@target` - optional
**Description and Usage:**
The `<list>` element is used for general lists that can be embedded with a large number of descriptive elements.
To encode a simple list, include one or more `<item>` elements within `<list>`. To encode more complex list, such as hierarchies, additional `<list>` elements can be included within `<list>`, with `<item>` included within the child `<list>` elements. `<head>` can be used to encode a title or caption within a `<list>`.
**Attribute Usage:** Use `@listType` to identify and format the list as a particular type. The choices are: "ordered," and "unordered."
**See Also:** Do not confuse with `<chronList>`, which encodes a structured chronology.
**Availability:** Optional, Repeatable

**Comment by ailie-s** [comment]
@SJagodzinski  and @fordmadox  - can we confirm the availability of `<item>` within `<list>`?

#176 says `<item>` is required, the schema says item is required, but `<list>` says item (0..n). 

Could there be a use case where a `<list>` contains only child <list> elements but no `<item>`s?

**Comment by SJagodzinski** [comment]
@ailie-s : `<item>` within `<list>` is optional after we decided to add `<list>` and `<head>` as child elements of `<list>.` You may have a `<list>` with only one <list> element as child but no `<item>`. I'll edit #176

**Comment by fordmadox** [comment]
I had made "item" required before, but I can update that now in the schema so we can try out a fully-optional approach.  

I think that I still prefer the list-in-item approach used by HTML, markdown, etc., but we should look at what this new list-in-list approach means for migration and conversion to other display formats.  I haven't investigated that yet, but I suspect that will just mean adding in an empty "item" element as needed during the conversion for any embedded lists, unless a head or item element is also present prior to the embedded list.

**Comment by fordmadox** [comment]
I also think we'll need to grapple with the "deflist" option.  It has always confused me that EAD had that as an attribute rather than an element name, since the only way to actually have a definition list is to use the defitem element (which has the label and item pair of elements as children), but EAC hasn't added "defitem" + "label" as elements, so why have the deflist option?  

Again, I'd prefer mirroring HTML here (if not outright importing the XHTML standard, although that could still be done in a locally-scoped version of EAD/C).  So, in EAC (and then EAD) that would mean:

- Removing "deflist" as a `@listtype` option;
- Optionally creating real definition list elements (not just for defitem, but also deflist)

And if we don't do the latter, we just don't support definition lists.  But the following is meaningless in the EAC 2.0 draft, I'd say:

```
          <list listType="deflist">
              <item></item>
          </list>
```

And in EAD, you can have conflicting markup like:

```
          <list listtype="deflist">
              <item></item>
          </list>
          <list listtype="unordered">
              <defitem>
                  <label></label>
                  <item></item>
              </defitem>
          </list>
```

**Comment by kerstarno** [comment]
With regard to "outright importing the XHTML standard": I think, if this is something that we want to do, we should decide upon it - or just leave the issue be. It's been floated in various contexts throughout the whole year, but never really landed, so my gut feeling is that there's not that much pick up for the idea. 

As for "deflist": in my opinion, this is one of those EAD approaches, for which I'd like to get an understanding if it is used and how it is used and to which extent it is used in the community. Maybe we could leave the value "deflist" out of the EAC-CPF 2.0 draft?

**Comment by kerstarno** [comment]
Tested as part of Schema team schema testing:

- `<list>` is available as an optional sub-element of `<biogHist>`, `<generalContext>`, and `<structureOrGenealogy>` as well as within `<list>` itself
- `<list>` can be used with the sub-elements `<head>`, `<list>`, and `<item>` with the latter two being repeatable
- as all sub-elements of `<list>` are optional, an encoding such as `<list></list>` is valid, too
- `<list>` can be used with the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, `@localType`, `@localTypeDeclarationReference`, `listType`, `@mark, `@numeration`, as well as attributes from any other namespace (tested with XLink)
- the attribute `@listType` can be used with the values "ordered" and "unordered" - "deflist" has been removed
- the attribute `@mark` can be used with the values "circle",  "disk", "inherit", "none", "square"
- the attribute `@numeration` can be used with the values "armenian", "decimal", "decimal-leading-zero", "georgian", "inherit", "lower-alpha", "lower-greek", "lower-latin", "lower-roman", "upper-alpha", "upper-latin", "upper-roman"

The above applies to both, the RNG and the XSD schemas. 

**Question:** Looking at the values for `@numeration`, I was wondering why we have lower _and_ upper for alpha, latin, and roman, but only lower for greek. @SJagodzinski and @fordmadox - should we add "upper-greek" as an option? This would then also apply to EAD.

Element ready to go, apart from the question raised with regard to adding the value "upper-greek" to `@numeration`.

**Comment by kerstarno** [comment]
As part of the testing, I've also created an example family tree following the branch of "Johannes Bach I" as illustrated here: https://en.wikipedia.org/wiki/Bach_family#Partial_family_tree. Please note, that this is only using the elements at the moment, i.e. we might want to extend this with some additional attributes in case we would want to use this in the TL and/or Best Practice Guide.

```
<list>
  <head>Bach family</head>
  <list>
    <item>Johannes Bach I (1580–1626)</item>
    <list>
      <item>Heinrich Bach (1615–1692)</item>
      <list>
        <item>Johann Christoph Bach (1642–1703)</item>
        <list>
          <item>Johann Nicolaus Bach (1669–1753)</item>
        </list>
      </list>
      <list>
        <item>Johann Michael Bach (1648–1694)</item>
        <list>
          <item>Maria Barbara Bach (1684–1720)</item>
          <list>
            <head>Marriage with Johann Sebastian Bach</head>
            <item>Wilhelm Friedemann Bach (1710–1784)</item>
            <item>Carl Philipp Emanuel Bach (1714–1788)</item>
            <list>
              <head>Marriage with Johanna Maria Dannemann</head>
              <item>Johann Sebastian Bach (painter) (1748–1778)</item>
            </list>
          </list>
        </list>
      </list>
    </list>
    <list>
      <item>Christoph Bach (1613–1661)</item>
      <list>
        <item>Johann Ambrosius Bach (1645–1695)</item>
        <list>
          <head>Marriage with Maria Elisabeth Lämmerhirt (1644–1694)</head>
          <item>Johann Sebastian Bach (1685–1750)</item>
          <list>
            <head>First marriage with Maria Barbara Bach (1684–1720)</head>
            <item>Wilhelm Friedemann Bach (1710–1784)</item>
            <item>Carl Philipp Emanuel Bach (1714–1788)</item>
            <list>
              <head>Marriage with Johanna Maria Dannemann</head>
              <item>Johann Sebastian Bach (painter) (1748–1778)</item>
            </list>
          </list>
          <list>
            <head>Second marriage with Anna Magdalena Wilcke (1701–1760)</head>
            <item>Gottfried Heinrich Bach (1724–1763)</item>
            <item>Johann Christoph Friedrich Bach (1732–1795)</item>
            <list>
              <head>Marriage with Lucia Elisabeth Münchhausen (1728–1803)</head>
              <item>Anna Philippiana Friederica Bach (1755–1804)</item>
              <list>
                <head>Marriage with Wilhelm Ernst Colson</head>
                <item>Children</item>
              </list>
              <item>Wilhelm Friedrich Ernst Bach (1759–1845)</item>
              <list>
                <head>Marriage with Charlotte Philippina Elerdt (1780–1801)</head>
                <item>Carolina Augusta Wilhelmine Bach (1800–1871)</item>
                <list>
                  <head>Marriage with Ludwig Albrecht Hermann Ritter</head>
                  <item>Children</item>
                </list>
                <item>Juliane Friederica (b. 1800)</item>
              </list>
              <item>Christina Luise Bach (d. 1852)</item>
            </list>
            <item>Johann Christian Bach (1735–1782)</item>
            <item>Elisabeth Juliane Friederica (1726–1781)</item>
            <list>
              <head>Marriage with Johann Christoph Altnickol (1720–1759)</head>
              <item>Johann Sebastian Altnickol (1749–1749)</item>
            </list>
            <item>Johanna Carolina (1737–1781)</item>
            <item>Regina Susanna (1742–1809)</item>
          </list>
        </list>
        <item>Johann Christoph Bach (1645–1693)</item>
      </list>
    </list>
  </list>
</list>
```

**Comment by SJagodzinski** [comment]
> **Question:** Looking at the values for `@numeration`, I was wondering why we have lower _and_ upper for alpha, latin, and roman, but only lower for greek. @SJagodzinski and @fordmadox - should we add "upper-greek" as an option? This would then also apply to EAD.

Upper-greek is not supported by HTML as far as I can see. Do we want to add it anyway?

**Comment by kerstarno** [comment]
I would have thought, these values are coming from CSS rather than from HTML. According to this page here, it would seem that the most common browsers do support "upper-greek": https://www.w3schools.com/cssref/pr_list-style-type.asp

**Comment by fordmadox** [comment]
It's easy enough to add more options to what's there now (and if we have lower-greek, I'm fine with adding upper-greek, of course), but what about one of the following two options, instead:

1) move these options to the Schematron.  I'm not sure, upon reflection, why EAD3 would include the CSS values in its base schema, but move ISO standards (e.g. for country codes) to the Schematron.  If the ISO lists are in the Schematron, why not the CSS list?

2) slightly more radical (at least for EAD):  don't add "mark" and "numeration" to EAC at all.  Given that we use the "style" attribute elsewhere to park CSS declarations, we could add the "style" attribute to "list" (we already have a TL example for font-style:italics, so why not `<list style="list-style-type: symbols(cyclic '○' '●')">`?, which you can also do in HTML/CSS, but not EAD.

I'd vote for option 2, but I also really like option 1 rather than adding more values to the base schema (but I do wonder if we should add other list-style-type values, in that case, like 'cambodian', etc.).

**Comment by kerstarno** [comment]
Didn't mean to start a principle discussion, just seemed weird that we had "upper"-variants for all other options, but not for Greek.

That being said: as Mark's suggestion touches on the general question of "how much formatting should actually be done by the EAS schemas directly?", I personally would support option 2 as this could be a means of still allowing for this, but bringing it down to a minimalistic approach. Furthermore, using `@style` instead of `@mark` and `@numeration` would also be a possible answer to the question I raised in the Schema Team's overview table with regard to possibly putting in a Schematron rule to ensure that only `@mark` or only `@numeration` is being used with one `<list>`.

**Comment by fordmadox** [comment]
As for why upper-greek is not in EAD3, that's because EAD3 uses this official list:  https://www.w3.org/TR/2011/REC-CSS2-20110607/generate.html#list-style   I can't find anywhere that this list has been updated officially, but it's certainly not all inclusive of how folks might want to format their lists (especially in an international context). And web browsers will support a lot more than that official list of values.

**Comment by fordmadox** [comment]
Again, not an official list from the CSS standard, but a very helpful / initimidating grid of browser support for list-style-type values on Mozilla's website:  https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type#browser_compatibility. 

What do you think of the option of going with `@style` instead, @SJagodzinski ?  If you like that idea, I could create a GitHub issue as a proposal.  Or we could keep things as is using the approved list from CSS2, as is now done in EAD3.

**Comment by SJagodzinski** [comment]
I agree with both approachs, moving mark and numeration options to Schematron and using `@style` instead of `@mark` and `@numeration`. If we take the `@style` option, this might be a general formatting approach for design principles.

@fordmadox : Do you want to realise this before the call for comments?

**Comment by kerstarno** [comment]
P.S. @fordmadox: Let me know, once you've removed `@mark` and `@numeration` and added `@style` instead and I'll do another quick schema test. Thank you :-)

**Comment by fordmadox** [comment]
Just updated, @kerstarno.  The only open question (which we don't need to answer now) is whether `@style` should be added anywhere else, or if it's even needed on list, if users could also handle that with attributes like `@localType`.  Either way, I think it's important to not restrict values for what CSS calls the list-style-type (which is a combo of EAD's 'mark' and 'numeration' options, plus more).

**Comment by MicheleCombs** [comment]
I'd argue for retaining `@style`.  IMO it has a very distinct semantic meaning that ought not to be muddled in with localtype -- style refers to visible formatting/layout e.g. alpha, bullet, etc, with a relatively limited number of options, while localtype is more of an intellectual concept and has a much wider range of possible values.  Analogous to how a book can be hardcover (style) as well as fiction or poetry or textbook or instruction manual or or or... (localtype).  Or a vinyl disc can be 33 1/3 and jazz or rock or speech or concert or home recording or propaganda or or or or...

At least that's how I've always thought of it.  I could be totally wrong :)

Michele

Sent from Nine<http://www.9folders.com/>

________________________________

**Comment by kerstarno** [comment]
@fordmadox - thanks for the update, will have another look and re-test.

As for `@localType`, I agree with @MicheleCombs that this would not be the appropriate place to deal with formatting. I would keep `@style` as it is right now: data type "string" and with the TL saying that "it is recommended that the value conforms to W3C CSS." This way, it can be applied to `<span>` e.g. for "bold" or "italic" as well as to `<list>`. And, looking at the question of EAS alignment and the question of "`<span>` vs. `<emph>`", I would rather not have us add `@style` to any other elements.

**Comment by fordmadox** [comment]
Thanks, @MicheleCombs!  

In this case, we are also _adding_ `@style` to a new element, since that attribute was only available as part of "span" in EAC 1.x (see https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN.html#attr-style).  And the recommendation is to keep the semantics of "style" associated with CSS, although there is no validation in place to try to determine that (due to the complexity of CSS, its different variations, as well as extensions for different web browsers, etc.).  

Does that also fit with your thinking?

My comment about `@style` in relation to `@localType` was going back to previous discussions about whether formatting elements and attributes could be eliminated entirely from EAC (e.g. rather than adding styling to the XML document, assign a different type -- e.g. `@localType="khmer-list"` - to anything you want formatted differently, since the formatting can be handled externally from the EAC XML file).  But when this data can be associated with CSS (particularly the formatting elements, like paragraph, list, etc.), I can also see the use case of being able to mix different styling options directly in the XML (e.g. `@style="list-style-type:khmer"`, where "list-style-type" is a CSS declaration), even if those styling attributes might only be used internally since who knows what will be added to that attribute (just like there's no great way to know what's being added to the localType attributes, even though those can be defined a bit more in the control section.... but that gets repeated in each file)?  Anyhow, I personally still have confusion around using an attribute named "localType" to define types that are not always "quote unquote" local, but that might just be my own personal confusion 😄 .  

And it's also why we are so eager to get examples of how folks might be using localtype.  Do you have any examples encoded in EAD3 or EAC that use `localType` in the way that you referenced, e.g. tagging something as an "instruction manual" via that attribute?

**Comment by kerstarno** [comment]
Re-tested:
- `@mark` and `@numeration` are not available anymore with `<list>`
- instead, `<list>` now allows for the optional attribute `@style`, which could (though should, of course, not) be left empty and could have any text string (which would later on go with the recommendation of using values associated with CSS)

Element is ready.
