### ISSUE TITLE
@localTypeDeclarationReference

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#175]
## Local type declaration reference

Add new optional attribute `@localTypeDeclarationReference` with data type IDREF in all elements alongside the attribute `@localType`

With `@localTypeDeclarationReference` a direct link to a local type declaration element within cpf/control/localTypeDeclaration can be provided. The attribute should always be used when `@localType` is used, in order to link to the local type definition.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
`<agencyCode>:` add attribute `@type` #15
Add local identifier attribute #45

## EAD3 Reconciliation
New EAS attribute

## Context
New EAS attribute

## Solution documentation: agreed solution for TL and guidelines
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed

**Data type**: IDREF

**May occur within**: `<abstract>`, `<address>`, `<addressLine>`, `<biogHist>`, `<chronItem>`, `<chronItemSet>`, `<chronList>`, `<componentEntry>`, `<contact>`, `<contactLine>`, `<date>`, `<dateRange>`, `<dateSet>`, `<event>`, `<existDates>`, `<fromDate>`, `<function>`, `<functions>`, `<generalContext>`, `<identityId>`, `<item>`, `<languageUsed>`, `<languagesUsed>`, `<legalStatus>`, `<legalStatuses>`, `<list>`, `<localControl>`, `<localDescription>`, `<localDescriptions>`, `<mandate>`, `<mandates>`, `<nameEntry>`, `<nameEntrySet>`, `<occupation>`, `<occupations>`, `<otherAgencyCode>`, `<otherEntityType>`, `<otherRecordId>`, `<part>`, `<place>`, `<placeName>`, `<places>`, `<relationType>`, `<representation>`, `<span>`, `<targetRole>`, `<toDate>`

- Example needed
- Topic for Best Practise Guide

## Example encoding

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** Use `@localTypeDeclarationReference `to provide a direct link to a `<localTypeDeclaration>` element within `<control>` from another element using `@localType` within the EAC-CPF instance. `@localTypeDeclarationReference` should always be used when `@localType` is used, in order to link to the local type definition.
**Data type:** IDREFS

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@localTypeDeclarationReference` is an optional attribute for (currently) 49 elements (`<abstract>`, `<address>`, `<addressLine>`, `<biogHist>`, `<chronItem>`, `<chronItemSet>`, `<chronList>`, `<componentEntry>`, `<contact>`, `<contactLine>`, `<date>`, `<dateRange>`, `<dateSet>`, `<event>`, `<existDates>`, `<fromDate>`, `<function>`, `<functions>`, `<generalContext>`, `<identity>`, `<identityId>`, `<item>`, `<languagesUsed>`, `<languageUsed>`, `<legalStatus>`, `<legalStatuses>`, `<list>`, `<localControl>`, `<localDescription>`, `<localDescriptions>`, `<mandate>`, `<mandates>`, `<nameEntry>`, `<nameEntrySet>`, `<occupation>`, `<occupations>`, `<otherAgencyCode>`, `<otherEntityType>`, `<otherRecordId>`, `<part>`, `<place>`, `<placeName>`, `<places>`, `<relationType>`, `<representation>`, `<span>`, `<structureOrGenealogy>`, `<targetRole>`, `<toDate>`)
  - That adds `<identity>` and `<structureOrGenealogy>` to the elements listed in the solution documentation above. @SJagodzinski seeing that these two have `@localType` in EAC-CPF 1.0 and we decided to keep `@localType` where available outside of `<control>`, I'm assuming this is correct. Could you please confirm? 
- Its data type is _IDREFS_
- It's always available together with the attribute `@localType`.

The above applies to both schemas, RNG and XSD. 

@ailie-s the data type has recently changed to IDREFS in order to allow for several IDs to be pointed to within one attribute.

**Comment by SJagodzinski** [comment]
>   * That adds `<identity>` and `<structureOrGenealogy>` to the elements listed in the solution documentation above. @SJagodzinski seeing that these two have `@localType` in EAC-CPF 1.0 and we decided to keep `@localType` where available outside of `<control>`, I'm assuming this is correct. Could you please confirm?

Yes, I that's correct.

**Comment by kerstarno** [comment]
@SJagodzinski thanks for the confirmation. 

With this, the attribute is ready.
