### ISSUE TITLE
<dateRange>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#180]
## Date Range
- add optional attributes
`@audience` 
`@conventationDeclarationReference` 
`@localTypeDeclarationReference` 
`@maintenanceEventReference`
`@sourceReference` 
`@target`
- keep name and scope
- topic for Best Practise Guide

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Topic_dates_20200911.pdf](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/dates/Topic_dates_20200911.pdf)
`<date>:` add `@certainty` #75
`<dateRange>:` best practice #32

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@script` - Optional

## Context
**Summary:** The date range of an event in the history of, or a relationship with, the person, family, or corporate body being described in the EAC-CPF instance. It contains `<fromDate>` and `<toDate>` child elements.
**May contain**: `<fromDate>`, `<toDate>`
**May occur within**: chronItem, cpfRelation, dateSet, existDates, function, functionRelation, legalStatus, localControl, localDescription, mandate, occupation, place, resourceRelation, useDates
**Attributes:**
`@localType` - Optional
`@x ml:id` - Optional
`@xml:lang` - Optional
**Availability**: Optional, Repeatable

## Solution documentation: 

**May contain**: `<fromDate>`, `<toDate>`
**May occur within**: chronItem, dateSet, existDates, function, legalStatus, localControl, localDescription, mandate, occupation, place, useDates
**Attributes:**
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional

**Availability**: Optional, Repeatable

- Topic for Best Practise Guide

## Example encoding
```
<dateRange audience="external" conventionDeclarationReference="cd1" id="dr1" languageOfElement="en" localType="localdaterange" localTypeDeclarationReference="ltd1" maintenanceEventReference="me1" scriptOfElement="lat" sourceReference="s1" target="element1">
 <fromDate standardDate="1906">1906</fromDate> 
 <toDate standardDate="1975">1975</toDate>
</dateRange>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A wrapper element for binding together `<fromDate>` and `<toDate>` in order to represent a range of dates.
**May contain:** fromDate (0..1), toDate (0..1)
**May occur within:** chronItem, dateSet, existDates, function, legalStatus, localControl, localDescription, mandate, occupation, otherEntityType, place, relation, useDates
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id `- optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:**
An element that expresses inclusive dates of an event in the history of, or a relationship with, the person, family, or corporate body being described in the EAC-CPF instance.
`<dateRange>` contains `<fromDate>` and/or `<toDate>`, and therefore may express a range of dates as a starting point with no end point, a start and end point, or an end point with no starting point. The content of the children of `<dateRange>` is intended to be a human-readable, natural language expression of the date. If, however, indexing or other machine processing of dates is desired, `@standardDate` should be used on the children of `<dateRange>` to record the date in machine-processable form as well.
Dates of existence for the identity being described in the EAC-CPF instance are encoded with the `<existDates>` element, while the dates of use of a particular name of an identity are encoded in `<useDates>`. The date and time of a maintenance event in the history of the EAC-CPF instance are given in the `<eventDateTime>` element.
**Attribute Usage:**
Use `@localType` to supply a more specific characterization of the date range.
Use `@standarddate` to provide a machine-processable form of the date.
**Availability**: 
Within `<function>`, `<legalStatus>`, `<localDescription>`, `<mandate>`, `<occupation>`, `<otherEntityType>`, `<place>`, `<relation>`: one of `<date>`, `<dateRange>` or `<dateSet>` optional, not repeatable
Within `<existDates>` and `<useDates>`: one of `<date>`, `<dateRange>` or `<dateSet>` required, not repeatable
Within `<dateSet>`: at least two of `<date>` and/or `<dateRange>` required, repeatable
Within `<chronItem>`: one of `<date>` or `<dateRange>` required, not repeatable
Within `<localControl>`: one of `<dateRange>` or `<date>` optional, not repeatable

**Comment by karinbredenberg** [comment]
Test of element dateRange:
May contain: fromDate (0..1), toDate (0..1) **Ok in both schemas but gives that it also can be empty and still validate**
Within function, legalStatus, localDescription, mandate, occupation, place: one of date, dateRange or dateSet optional, not repeatable  **Ok in both schemas**
Within existDates and useDates: one of date, dateRange or dateSet required, not repeatable **Ok in both schemas**
Within dateSet: at least two of date and/or dateRange required, repeatable **Ok in both schemas**
Within chronItem: one of date or dateRange required, not repeatable **Ok in both schemas**
Within localControl: one of dateRange or date optional, not repeatable **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@conventationDeclarationReference - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@localType - optional **Ok in both schemas**
@localTypeDeclarationReference - optional **Ok in both schemas**
@maintenanceEventReference - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@sourceReference - optional **Ok in both schemas**

**Result**: With having both toDate and fromDate as optional it means that the element can be empty and it still validates. Does this mean it should be mandatory to have one of the subelements? @ailie-s @fordmadox @SJagodzinski  All other test ok.

**Comment by fordmadox** [comment]
@karinbredenberg I was wondering the same thing regarding whether or not we should force a subelement.  Right now, I'm pretty sure that `daterange` | `dateRange` is defined the same way in EAD3 and EAC-CPF (current version).  

As things stand now, this is valid in EAD3:

```
<daterange altrender="the best date range of all time"/>
```

Because of that, I'd be in favor of making a change here.

**Comment by SJagodzinski** [comment]
I can confirm, that `<dateRange>` must have one child element, either `<fromDate>` or `<toDate>`, cf https://github.com/SAA-SDT/eac-cpf-schema/issues/32#issuecomment-690897589. 

@fordmadox : In this case, I personally would even define the child elements order (fromDate before toDate).

**Comment by fordmadox** [comment]
Updated with https://github.com/SAA-SDT/eac-cpf-schema/commit/c32d9ed377f25cded24b9dd2558cc42936be8b20, so this can be tested again, @karinbredenberg .

Of course, this still means that something like the following is valid, which isn't much different (although we could use the schematron, if desired, to enforce either a specific attribute or text):

```
                    <dateRange>
                        <toDate></toDate>
                    </dateRange>
```

**Comment by karinbredenberg** [comment]
Retest of eleemnt:

One child is needed.

**REsult** eleemtn ready
