### ISSUE TITLE
<placeRole>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#186]
## Place Role

- keep name and scope
- add optional attributes:
`@audience`
`@conventationDeclarationReference`
`@maintenanceEventReference` 
`@sourceReference` 
`@valueURI` 
`@vocabularySourceURI` 
- remove attributes lastDateTimeVerified, scriptCode, and transliteration

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
EAC-CPF specific element

## Context
**Summary**: An element to identify the contextual role a place or jurisdiction encoded in `<place>` elements has in relation to the CPF entity.
**May contain**: [text]
**May occur within**: place
**Attributes**: lastDateTimeVerified, scriptCode, transliteration, vocabularySource, xml:id, xml:lang - all optional
**Availability:** Optional, Non-repeatable

## Solution documentation: agreed solution for TL and guidelines

**May contain**: [text]
**May occur within**: `<place>`
**Attributes**: 
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional

**Availability:** Optional, not repeatable

## Example encoding
```
<place> 
 <placeName>name of the place</placeName> 
 <placeRole audience="external" conventionDeclarationReference="conventiondeclaration1" id="placeRole1" languageOfElement="en" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1" valueURI="http://vocabularySource.uri/placeRole" vocabularySourceURI="http://vocabularySource.uri" vocabularySource="sourceofvocabulary">example place</placeRole>
</place>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional child element of `<place>` used to identify the contextual role the place or jurisdiction has in relation to the CPF entity described in the EAC-CPF instance.
**May contain:** [text]
**May occur within:** place
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI `- optional
**Description and usage:**
`<placeRole>` provides a contextual role for a `<placeName>` within `<place>`. Places should be identified in `<placeName>` by the proper noun that commonly designates the place, natural feature, or political jurisdiction. It is strongly recommended that each place name is accompanied by a `<placeRole>` element in order to describe the nature of the association of the place to the CPF entity.
**Attribute usage:**
The `@vocabularySource` attribute may be used to indicate the controlled vocabulary from which the `<placeRole>` is derived.
**Availability:** Optional, not repeatable

**Comment by karinbredenberg** [comment]
Test of element placeRole:
May occur within: place 0..1 **in both schemas 0..n**
May contain: [text] **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@conventationDeclarationReference - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@maintenanceEventReference - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@sourceReference - optional **Ok in both schemas**
@valueURI - optional **Ok in both schemas**
@vocabularySource - optional **Ok in both schemas**
@vocabularySourceURI - optional **Ok in both schemas**
@target - optional **Added in both schemas**

**Result**: Cardinality needs to be changed to not repeatable. @lastDateTimeVerfied needs to be removed. @target has been added.

**Comment by fordmadox** [comment]
Just a note that placeRole included @lastDateTimeVerified in EAC-CPF 1.0.  See https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN.html#elem-placeRole. 

If removed, we'll need to add documentation about that to the transformation tool, as well.  

To do:  check and see if there are any uses of that attribute on placeRole in current EAC test corpus.

**Comment by fordmadox** [comment]
We might also need to update TL definition.  Currently says: "It is strongly recommended that each place **name** is accompanied by a `<placeRole>` element...", but if placeName is repeatable and placeRole is not, then we might need to change that to something like:  "It is strongly recommended that each place **element** is accompanied by a `<placeRole>` element..."

**Comment by fordmadox** [comment]
Also, not sure if we're testing a few of these elements too early or not, but the definition of place indicates that placeRole can occur more than once:

"May contain: address (0..n), contact (0..n), date (0..n), dateRange (0..n), dateSet (0..n), descriptiveNote (0..1), geographicCoordinates (0..n), placeName (0..n), **placeRole (0..n)**, reference (0..n)"

@karinbredenberg , @ailie-s : I'll remove the lastDateTimeVerified attribute now, but keep the cardinality the same until I know whether it should be repeatable or not.

**Comment by SJagodzinski** [comment]
@fordmadox : Having `<placeRole>` repeatable might be useful for translation/multilingualism. There is also a chance to have more than one role for a mentioned place, eg an address where someone was born and lived for a range of time.

**Comment by kerstarno** [comment]
With regard to `<placeRole>` within `<place>`, #185 includes the definition as per the decision on 6 November: "Require <place> to have at least one of the following sub-elements: `<placeName>`, `<placeRole>`, `<address>`, `<contact>`, `<geographicCoordinates>`" with each of these being repeatable. 

As for `@lastDateTimeVerified`: can't remember if we did decide on this in the end, but I seem to remember having talked about the question if this attribute actually should go along with any elements that can include external links of any type, i.e. `@href`, `@valueURI`, `@vocabularySourceURI`.

**Comment by fordmadox** [comment]
Okay, great!  Thanks for confirming.  Then both the RNG and XSD schemas should be all set for place, and the cardinality test can be re-run @karinbredenberg since it's been confirmed that placeRole can repeat.  

Right now, I think the decision was to bind lastDateTimeVerfied to href, but I don't see why the other two *URI attributes wouldn't also apply, which would mean that placeRole gets to keep that attribute (if so, I can add it back, but for the time being the schemas reflect this issue as it is now, so that attribute has been removed).

**Comment by SJagodzinski** [comment]
> Right now, I think the decision was to bind lastDateTimeVerfied to href, but I don't see why the other two *URI attributes wouldn't also apply, which would mean that placeRole gets to keep that attribute [...]

True and we decided to leave `@lastDateTimeVerified` from the other two URI attributes as there is not use case. I also think that we expect persistent URIs in `@vocabularySourceURI` and in `@valueURI` but maybe more temporary adresses in @href. Anyway, to finalise this draft, lets keep `@lastDateTimeVerified` only bound to `@href`.

**Comment by karinbredenberg** [comment]
Retest of element:
Cardinality 0..n **Ok in both schemas**

**Result**: Element ready.
