### ISSUE TITLE
@addressLineType

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#191]
## Address Line Type

Add the new optional attribute `@addressLineType` with limited values in `<addressLine>` to specify the type of the addressline. 

Values: county, country, district, municipality, postBox, postalCode, region, street

Use the attribute `@localType` in order to encode a local type of an address line.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
new EAC-CPF attribute

## Context
new EAC-CPF attribute

## Solution documentation: agreed solution for TL and guidelines
_Summary_ needed

Data Type: "county" or "country" or "district" or "municipality" or "postBox" or "postalCode" or "region" or "street"

**May occur within**: `<addressLine>`

- use the attribute `@localType` in order to encode a local type of an address line.
- example needed

## Example encoding
`<addressLine addressLineType="street">8601 Adelphi Road</addressLine>`

**Comment by kerstarno** [comment]
Haven't checked the ERMS document yet, which was linked in the "Place encoding" document, but I'm not sure about "city" and "postBox" as additions. How would we explain the difference between these two and "municipality" and "postalCode"?

**Comment by kerstarno** [comment]
Finally got around to checking the document in more detail. I still don't see why we could add "city". ERMS suggests "postal_city", but it also uses "municipality" for the city or town where the address is found. I would go along with "postBox", though. 

As an additional note: ERMS uses "province" instead of "region", but if I remember the conversations in the Archives Portal Europe context correctly, "province" had a very specific administrative connotation, which works in some, but not all contexts, hence I'd still prefer "region".

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** Used to specify the type of address line encoded in `<addressLine>`.
**Description:** Use one of the set values to specify the type of address line encoded in `<addressLine>`. Use the attribute `@localType` in order to encode a local type of an address line.
**Data values:** county, country, district, municipality, postBox, postalCode, region, street

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@addressLineType` is an optional attribute in `<addressLine>`
- It can have the values "country", "county", "district", "municipality", "postBox", "postalCode", "region", and "street"
- It has the data type _token_

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
