### ISSUE TITLE
<localDescription>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#200]
## Legal Status

- keep name and scope
- add optional attributes
`@audience` 
`@conventationDeclarationReference` 
`@localTypeDeclarationReference` 
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference`
`@valueURI` 
`@vocabularySource` 
`@vocabularySourceURI` 
- change availability to mandatory, repeatable

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
Role and function of singular/plural elements is confusing #21
Child elements of singular/plural elements #61

## EAD3 Reconciliation
EAC-CPF specific element

## Context
**Summary**: Used to extend the descriptive categories to others available in a local system. Its meaning will depend on the context in which it occurs.
**May contain**: citation, date, dateRange, dateSet, descriptiveNote, placeEntry, term
**May occur within**: description, functions
**Attributes**: localType, xml:id, xml:lang - all optional
**Availability**: Optional, Repeatable

## Solution documentation:

**May contain**: `<date>`, `<dateRange>`, `<dateSet>`, `<descriptiveNote>` (0..1), `<placeName>` (0..n), `<term>` (0..n)
**May occur within**: `<localDescriptions>`
**Attributes**:
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional

**Availability**: required, repeatable

- new example needed

## Example encoding
```
<localDescriptions>
 <localDescription audience="external" conventionDeclarationReference="conventiondeclaration1" id="localDescription1" languageOfElement="en" localType="locallocaldeclaration" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenanceagency1" scriptOfElement="lat" sourceReference="source1" valueURI="http://localdescriptionterm.org" vocabularySource="localvocabulary" vocabularySourceURI="http://localvocabulary.org">
  <term>term of a local description</term>
  <placeName>place related to a local description</placeName>
  <date>1970</date>
  <reference>external reference for a local description</reference>
  <descriptiveNote>
   <p>note for this local description</p>
  </descriptiveNote>
 </localDescription>
</localDescriptions>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A required child element of `<localDescriptions>` used to extend the descriptive categories to others available in a local system.
**May contain:** date or dateRange or dateSet (0..1), descriptiveNote (0..1), placeName (0..n), term (1..n)
**May occur within:** localDescriptions
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id `- optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI `- optional
**Description and Usage:**
`<localDescription>` provides a means to extend the list of description elements specified in the EAC-CPF schema. It should be used to record structured index terms rather than discursive text. The `<localDescription>` element should be used whenever  a separate semantic process of the descriptive information is required in a local system that cannot be accommodated by the existing categories available in EAC-CPF.
`<localDescription>` must contain at least one `<term>` child element. Terms may be drawn from controlled vocabularies or may be natural language terms. Associated date(s) (`<date>`, `<dateRange>` or `<dateSet>`) and place(s) (`<placeName>`) may be included to further constrain the term's meaning. A `<descriptiveNote>` may be included if a fuller textual explanation is needed.
**Availability:** required, repeatable

**Comment by karinbredenberg** [comment]
Test of element localDescription:
May occur within: localDescriptions 1..n **OK in both schemas**
**May contain:**date or dateRange or dateSet (0..1),  **OK in both schemas**
descriptiveNote (0..1),  **OK in both schemas**
placeName (0..n),  **OK in both schemas**
reference (0..1),  **OK in both schemas**
term (1..n) **OK in both schemas**
@audience - optional (values limited to: external, internal) **OK in both schemas**
@conventationDeclarationReference - optional **OK in both schemas**
@id - optional **OK in both schemas**
@languageOfElement - optional **OK in both schemas**
@localType - optional **OK in both schemas**
@localTypeDeclarationReference - optional **OK in both schemas**
@maintenanceEventReference - optional **OK in both schemas**
@scriptOfElement - optional **OK in both schemas**
@sourceReference - optional **OK in both schemas**
@valueURI - optional **OK in both schemas**
@vocabularySource - optional **OK in both schemas**
@vocabularySourceURI - optional **OK in both schemas**

**Result**: element ready

**Comment by kerstarno** [comment]
Note: Following the EAC Team meeting on 8 January, `<localDescription>` will not have `<reference>` as direct sub-element anymore. It's not listed for the TL draft, but the schema test confirms its availability. Needs to be rechecked.

**Comment by kerstarno** [comment]
Updated the schema (models-and-shared-elements.rng) and removed `<reference>` from the single elements model therein. 

Retested.

- `<localDescription>` does not allow for `<reference>` anymore as a direct sub-element in neither the RNG, nor the XSD

Element ready (again).
