### ISSUE TITLE
@target

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#216]
## Target

Add the new optional attribute `@target` with data Type IDREF to allow internal linking. 
Add `@target` next to `@id` as universal generic attribute to all elements except for `<eac>` (root element).

Data type: IDREF

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
Topic_Reference

## EAD3 Reconciliation
**Summary**: A pointer to the ID of another element. Used to create internal links within an XML instance. Available in `<ptr>` and `<ref>`.
Data Type: IDREF

## Context
new EAC-CPF attribute

## Solution documentation: 

**Summary**: A pointer to the ID of another element. Used to create internal links within an XML instance. Available in ... .

**Data Type**: IDREF

- example needed
- How to distinguish between using `<reference @href>` and `@vocabularyURI` / `@vocabularySourceURI`?
 Deal with this via documentation, i.e. `@vocabularyURI` / `@vocabularySourceURI` are used for links specifically to vocabularies, thesauri, ontologies, while `<reference @href>` is used for generic resources (e.g. Wikipedia page with `<reference @href>`, but `@vocabularyURI` for Wikidata ID) 

## Example encoding
example encoding to follow

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A pointer to the ID of another element. Used to create internal links within an XML instance. Available in all elements except `<eac>`.
**Data Type:** IDREFS

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing: 

- `@target` is available with 88 elements of EAC-CPF 2.0, i.e. all elements with the exception of `<eac>`
- Its data type is _IDREFS_
- It is always available alongside `@id`
- It is always available alongside `@audience`

The above applies to both schemas, RNG and XSD. 

The attribute is ready. 

@ailie-s the data type has recently changed to IDREFS in order to allow for several IDs to be pointed to within one attribute.
