### ISSUE TITLE
<setComponent>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#223]
## Set Component 

- review scope and usage: use cases from National Library of Australia - keep the element
- add optional attributes:
`@audience`
`@conventationDeclarationReference`
`@href`
`@lastDateTimeVerified`
`@linkRole`
`@linkTitle`
`@maintenanceEventReference`
`@scriptOfElement`
`@sourceReference`
`@target`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
alternativeSet / setComponent / componentEntry #154 

## EAD3 Reconciliation
EAC-CPF specific element

## Context
**Summary**: A wrapper element within `<alternativeSet>` that contains the EAC-CPF encoding for one entire authority record, thereby permitting the bundling of authority records from multiple authority systems within a single `<cpfDescription>.`
**May contain**: componentEntry, descriptiveNote, objectBinWrap, objectXMLWrap
**May occur within**: alternativeSet
**Attributes**: `@lastDateTimeVerified`, `@xlink:actuate`,  `@xlink:arcrole`, `@xlink:href`, `@xlink:role`, `@xlink:show`, `xl@ink:title`, `@xlink:type` - Required (if any XLINK attributes used), `@xml:id`, `@xml:lang` - nearly all optionalOptional
**Availability**: Mandatory, Repeatable

## Solution documentation: agreed solution for TL and guidelines

**May contain**: `<componentEntry>` (0..n), `<descriptiveNote>` (0..1), `<objectXMLWrap>` (0..1)
**May occur within**: `<alternativeSet>`
**Attributes**:
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@href` - optional
`@languageOfElement` - optional 
`@linkRole` - optional
`@linkTitle` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Availability**: Mandatory, Repeatable

## Example encoding
```
<alternativeSet>
 <setComponent audience="external" conventionDeclarationReference="convention1" href="www.externallink.com" id="sc1" languageOfElement="eng" lastDateTimeVerified="2021" linkRole="" linkTitle="link" maintenanceEventReference="maintance1" scriptOfElement="lat" sourceReference="source1" target="control1">
  <componentEntry>textual note about the EAC-CPF encoding for one entire authority record</componentEntry>
  <descriptiveNote>
   <p>note about the EAC-CPF encoding for one entire authority record</p>
  </descriptiveNote>
  <objectXMLWrap>
   <non-eas-xml xmlns="">
    <anyElement/>
   </non-eas-xml>
  </objectXMLWrap>
 </setComponent>
</alternativeSet>
```

**Comment by kerstarno** [comment]
Tested as part of schema testing:

- `<setComponent>` is a required sub-element of `<alternativeSet>`
- `<setComponent>` can be repeated
- `<setComponent>` can be used with the optional sub-elements `<componentEntry>` (repeatable and expected first), `<descriptiveNote>`, and `<objectXMLWrap>`
  - <del>@fordmadox Currently `<descriptiveNote>` is expected before `<objectXMLWrap>`, while it should be the other way round</del> (Edit: removed this comment as not applicable)
- `<setComponent>` can be used with the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, `@href`, `@linkRole`, `@linkTitle`, and `@lastDateTimeVerified` 
- `<setComponent>` also allows for optional attributes of any other namespace (tested with XLink)

The above applies to both schemas, RNG and XSD. 

<del>Pending the sequence correction for the sub-elements.</del> Update: The element is ready.

**Comment by kerstarno** [comment]
@fordmadox I've updated the eac-alternativeSet.rng in source (along with the RNG and XSD schemas for testing purposes) to alter the order of `<descriptiveNote>` (now last) and `<objectXMLWrap>` (now second to last)  as sub-elements of `<setComponent>`.

**Comment by ailie-s** [comment]
Draft Tag Library Text

**Summary:** A required child element of `<alternativeSet>` that contains the EAC-CPF encoding for one entire authority record, thereby permitting the bundling of authority records from multiple authority systems within `<cpfDescription>`.
**May contain:** componentEntry (0..n), descriptiveNote (0..1), objectXMLWrap (0..1)
**May occur within:** alternativeSet
**Attributes:** 
`@audience `- Optional (values limited to: external, internal)
`@conventionDeclarationReference `- Optional
`@href `- Optional
`@id `- Optional
`@languageOfElement `- Optional
`@lastDateTimeVerified `- Optional
`@linkRole `- Optional
`@linkTitle `- Optional
`@maintenanceEventReference `- Optional
`@scriptOfElement `- Optional
`@sourceReference `- Optional
`@target `- Optional
**Description and Usage:** `<setComponent>` provides a wrapper to contain an entire authority record, so that multiple records for the same identity from separate authority systems, or in different languages, may be combined together within a single EACCPF instance.
The `<componentEntry>` child element encodes the link to the authority record in the external system. An optional `<descriptiveNote>` may be used for a textual note providing further information about the record referenced in `<setComponent>`.
**Availability:** Required, repeatable
