### ISSUE TITLE
@functionRelationType

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#231]
##  Function Relation Type

Remove optional attribute `@functionRelationType`. 
The attribute was inherited in `<functionRelation>` element that was also removed from EAC and replaced by //targetEntity@targetType with limited values. 
`@functionRelationType` is replaced by new element `<relationType>`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Paper on Relation](https://github.com/SAA-SDT/TS-EAS-subteam-notes/tree/master/eaccpf-subteam/working-documents/topics/relations)

## EAD3 Reconciliation
EAC-CPF specific attribute

## Context
Decision from Berlin 2020 meeting to change the relation encoding.

**Summary**: The type of relation that the entity being described has to the related function.
**Description and Usage**: The functionRelationType may occur on `<functionRelation>.` The value designates the type of relation that the entity being described has to the related function. If the type of relation is more specific than one of the values given below, Xlink attributes may be used in addition to functionRelationType.
**Data Type**: "controls" or "owns" or "performs"

## Solution documentation

- remove from Tag Library

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing: 

- `@functionRelationType` is not available anymore in the draft schema for EAC-CPF 2.0

The above applies to both schemas, RNG and XSD. 

The attribute is ready.

**Comment by kerstarno** [comment]
@SJagodzinski, @fordmadox, @ailie-s, @gerhardmueller 

Similar to my comment for `@cpfRelationType` (#230), I'm wondering whether the current values for `@functionRelationType` ("controls" or "owns" or "performs") would all end up in `<relationType>` as suggested in #219, or if they would rather fit into `<targetRole>` (#220), though probably in their inverse forms seeing that `<targetRole>` specifies the role of the target towards the entity described, i.e. "controlledBy" or "OwnedBy" and "PerformedBy". And, in case we would keep the conversion route towards `<relationType>`, would we then rather say "control" or "ownership" and "performance" in order to use more general terms?

Any thoughts?

**Comment by SJagodzinski** [comment]
See https://github.com/SAA-SDT/eac-cpf-schema/issues/219#issuecomment-985367445
