### ISSUE TITLE
@resourceRelationType

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#239]
##  Resource Relation Type

Remove optional attribute `@resourceRelationType`. 
The attribute was inherited in `<resourceRelation>` element that was also removed from EAC and replaced by //targetEntity@targetType with limited values. 
`@resourceRelationType` is replaced by new element `<relationType>`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Paper on Relation](https://github.com/SAA-SDT/TS-EAS-subteam-notes/tree/master/eaccpf-subteam/working-documents/topics/relations)

## EAD3 Reconciliation
EAC-CPF specific attribute

## Context
Decision from Berlin 2020 meeting to change the relation encoding.

**Summary**: The type of relation of entity being described to the resource.

**Description and Usage**: The resourceRelationType may occur on `<resourceRelation>`. The value designates the type of relation that the entity described in the EAC-CPF instance has to the resource. If the nature of the relation is more specific than one of the available values, the Xlink attributes may be used in addition to resourceRelationType.

**Data Type**: "creatorOf" or "subjectOf" or "other"

## Solution documentation

- remove from Tag Library

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@resourceRelationType` is not available anymore in the draft schema for EAC-CPF 2.0

The above applies to both schemas, RNG and XSD. 

The attribute is ready.

**Comment by kerstarno** [comment]
@SJagodzinski, @fordmadox, @ailie-s, @gerhardmueller 

Similar to my comment for `@cpfRelationType` (#230), I'm wondering whether the current values for `@resourceRelationType` ("creatorOf" or "subjectOf" or "other") would all end up in `<relationType>` as suggested in #219, or if they would rather fit into `<targetRole>` (#220), though probably in their inverse forms seeing that `<targetRole>` specifies the role of the target towards the entity described, i.e. "createdBy" or "hasSubject" and "other". And, in case we would keep the conversion route towards `<relationType>`, would we then rather say "creation" or "subject" in order to use more general terms?

Any thoughts?

**Comment by SJagodzinski** [comment]
See https://github.com/SAA-SDT/eac-cpf-schema/issues/219#issuecomment-985367445
