### ISSUE TITLE
@value

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#256]
## Value

- add new mandatory attribute `@value` to `<entityType>` with limited values corporateBody, person, family

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
<entityType> #116

## EAD3 Reconciliation

**Summary**: General attribute, required in a number of children of <control>, that provides controlled terminology related to the management of an EAD instance. The terms available for value are defined in closed lists that vary by element as follows: [...]

## Context
new EAC attribute

## Solution documentation: 
_Summary_ needed

- defines the type of the described entity in an EAC instance

**Mandatory within**: `<entityType>`
**Values**:  corporateBody, person, family

## Example encoding
```
<identity>
 <entityType value="person"/>
 <nameEntry>
  <part>name of the person</part>
 </nameEntry>
</identity>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** Required attribute within the `<entityType>` element that defines the type of entity being described in the EAC-CPF instance.
**Values:** corporateBody, family, person

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@value` is a required attribute in `<entityType>`
  - @ailie-s the TL draft above says `<nameEntry>` instead of `<entityType>`
- It can have the values "corporateBody", "family", or "person"
- Its data type is _token_

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
