### ISSUE TITLE
Encode the relationship between a person and a date explicitly

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#267]
`<existDates>`: It should be possible to encode the relationship between a person and a date explicitly.

## Creator of issue
1. Gerhard Müller
2. Staatsbibliothek zu Berlin

## The issue relates to

- [x] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Add attributes `@vocabularySource`, `@vocabularySourceURI`, `@valueURI` to //date, //dateRange, //fromDate, //toDate

### example 1:
```
<dateRange>
    <fromDate vocabularySource="GND Ontology" vocabularySourceURI="https://d-nb.info/standards/elementset/gnd" valueURI="https://d-nb.info/standards/elementset/gnd#dateOfBirth">1906</fromDate>
</dateRange>
```
### example 2:
```
<dateRange vocabularySource="GND Ontology" vocabularySourceURI="https://d-nb.info/standards/elementset/gnd" valueURI="https://d-nb.info/standards/elementset/gnd#dateOfBirthAndDeath">
    <fromDate>1906</fromDate>
    <toDate>1975</toDate>
</dateRange>
```
### example 3:
```<date vocabularySource="GND Ontology" vocabularySourceURI="https://d-nb.info/standards/elementset/gnd" valueURI="https://d-nb.info/standards/elementset/gnd#periodOfActivity">1970</date>```

## Context
It should be possible to encode the relationship between a person and a date explicitly.

#144 , #179 , #180 , #181 , #182

**Comment by kerstarno** [comment]
As a note:

When the EAC-CPF team discussed about which elements should enable the three vocabulary attributes, the date elements (`<date>`, `<dateRange>`, `<fromDate>`, and `<toDate>`) ended up with a balanced vote, i.e. the same amount of "Yes" votes and "No" votes. The examples used in that context referred to "more general (and literal) date information such as 'New Year's Eve', 'Easter', 'Bastille Day', etc.". 

One argument for caution back then was "to postpone a decision with regard to dates and to wait for an outcome on events".

One argument against including vocabulary references in the date elements was that it would be preferable "to keep dates for dates, even when the date expression references a date that has an entry in a vocabulary.  I think it’s something that should be accommodated in another way, though. In MODS, you could have:
```
<subject>
  <temporal valueURI="http://id.loc.gov/authorities/subjects/sh85012296">Bastille Day</temporal>
</subject>
```
But not a qualifier on dateCreated.  I think that makes sense, since the Wikidata example isn’t for a specific Good Friday."

Mainly posting for reference as the example brought up here might fall into a different category and hence might result in a different decision.

**Comment by AMUnderhill** [comment]
In the date elements its possible to use @localType, does that not solve this problem?

**Comment by kerstarno** [comment]
`@localType` could be an option, if we mainly wanted to have the possibility to capture any qualifier for the date as a literal. The same would probably be true for the option to use attributes from any other namespace. 

The aspect suggested here, though, is about giving the URI for a qualifying term rather than encoding that term directly.

**Comment by SJagodzinski** [comment]
EAC-CPF meeting, 4 Nov 2021:

Recommend use `@localType` to encode context around a date/the type of date it is, link it back to `<localTypeDeclaration>`, which can include references. Include in Best Practice Guide in the relationship section and in the date section.
