### ISSUE TITLE
Remove xml ns to align with EAD 3

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#27]
Remove xml namespace to align with EAD 3, concerns the attributes `@xml:base`, `@xml:id`, `@xml:lang`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to
- [x] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
For alignment with EAD 3 remove xml namespace and define the concerned attributes:
`@xml:base` becomes `@base`
`@xml:id` becomes `@id`
`@xml:lang` becomes `@lang`

## Context
bring in alignment with EAD3, move away from xml namespace to provide more flexibility

**Comment by karinbredenberg** [comment]
Agreed! Changes in TL also needed when this is done.

**Comment by karinbredenberg** [comment]
Its a Phase-2 for me.

**Comment by SJagodzinski** [comment]
Meeting 18 Dec 2017 outcome:
Changing the namespace has a huge impact on the schema.
Will be moved to phase 2, revision, because it is not suitable for a technical update.

**Comment by kerstarno** [comment]
Just as a note - the Shared Schema subteam has been discussing a common approach to XML (and XLink) namespace as well. You can find our thoughts here: https://github.com/SAA-SDT/SharedSchema/issues/2.

**Comment by fordmadox** [comment]
Right now, EAC allows two options when using the pluralized versions for a few of those pluralized elements.  Option one allows you to have the singular element (1 or more) and a descriptive note (0 or 1).  Option two allows you to have the discursive set (e.g. citation, list, outline, p).  If we can get rid of having two options, I'm all for using the pluralized versions. 

There's also the issue of the singular elements that can repeat but *cannot* be grouped the same way, though:   generalContext, structureOrGenealogy, biogHist.

I'm perfectly fine with just grouping by element names while processing, however.  

That said, if we force "function" to be a child of "functions", why not "generalContext" as a child of "generalContexts", etc.  However, I'd still probably be in favor of just letting singular elements repeat without forcing them in a grouping element.   

Regardless, I think that this needs to be addressed, since I don't see any reason to keep the singular/plural distinction as it exists now in EAC.

**Comment by SJagodzinski** [comment]
Team discussion:
Removing the namespace simplifies the schema and xml handling.
There is no specific EAC-CPF requirement in respect with linking. 

Reusing a common vocabulary for these attributes seems useful. TS-EAS definition of attributes like @id and @base might not be that obvious.

Decision on namespace has to be made with the shared schema team and EAD team in order to get a consistent solution for both schemas.

**Comment by SJagodzinski** [comment]
see also [comparison report](https://docs.google.com/spreadsheets/d/13XT1lHfhEJiZ06KVeYtRu0f3ke20_9vZKoRuzKM-Ll0/edit#gid=347935402&range=B24:B26)

**Comment by SJagodzinski** [comment]
EAC-EAD-Schema joint meeting, 28 Jan 2020:

**xml namespace** still need to be discussed, esp. if `@base` would be used in EAD/EAC-CPF with the same scope than `@xml:base`. Decision postponed to Berlin meeting (March 2020).

**Comment by SJagodzinski** [comment]
EAC-CPF meeting, Berlin, 10 March 2020:

Hand a decision over to the Schema team to analyse the benefits and consequences of usage or removing of xml ns.

Will be discussed in one of the next [Schema team](https://github.com/SAA-SDT/TS-EAS-subteam-notes/tree/master/schemas-subteam) meetings.

**Comment by SJagodzinski** [comment]
Comment from @florenceclavaud on 9 March 2020 in the paper Topic: Relations:

> [...] BTW I would not remove xml namespace and would continue using xml:id, xml:lang and xml:base, as they havs been speficied by W3C. I think that removing XML namespace from EAD 3 is not a good decision).

**Comment by kerstarno** [comment]
Adding the comments that Mark already provided in the context of the Berlin meeting for reference:

- EAD never used the XML namespace, neither in EAD 1.0, nor in EAD 2002
- Also, EAC Beta did not use the XML namespace, but it was only added within EAC-CPF
- Another standard that has defined its own ID attribute, which seems to serve the same purpose as @xml:id, is METS

**Comment by SJagodzinski** [comment]
TS-EAS Chicago meeting, 4 August 2020:

Remove xml namespace but keep the attributes needed.

`@xml:id` becomes `@id` with data type ID.
`@xml:lang` becomes `@languageOfElement` with data type NMTOKEN.
`@xml:base` becomes `@base` with data type anyURI.

Availability will be defined for each attribute.
