### ISSUE TITLE
Disambiguate terms in <descriptiveNote>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#270]
It should be possible to disambiguate terms in `<descriptiveNote>` with `@vocabularySource`, `@vocabularySourceURI`, `@valueURI`.

## Creator of issue
1. Gerhard Müller
2. Staatsbibliothek zu Berlin

## The issue relates to

- [ ] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Add optional attributes `@vocabularySource`, `@vocabularySourceURI`, `@valueURI` to `<descriptiveNote>`.

### example:

```
<descriptiveNote vocabularySource="GND Ontology" vocabularySourceURI="https://d-nb.info/standards/elementset/gnd" valueURI="https://d-nb.info/standards/elementset/gnd#EarlierNameOfThePerson">
    <term languageOfElement="en">Earlier name of the person</term>
    <term languageOfElement="de">Früherer Name der Person</term>
</descriptiveNote>
```

## Context
Using vocabularies of an ontology to specify (in this case) the type of a name.

#109 , #269

**Comment by kerstarno** [comment]
See my note on the general context of the suggested change in #269. 

As for adding the vocabulary attributes to `<descriptiveNote>`, I would see this not being in line with the purpose of `<descriptiveNote>` as an element as well as not being in line with the purpose of the vocabulary attributes. If we wanted to follow the suggested change in #269, on which the change in this issue here builds, I'd rather think we should reconsider enabling the vocabulary attributes with `<term>`.

**Comment by SJagodzinski** [comment]
EAC-CPF meeting, 4 Nov 2021:

No change. Highlight in Tag Library that `<descriptiveNote>` is to be used for descriptive, not structured, content.
