### ISSUE TITLE
<placeEntry>: should be mandatory

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#4]
Make `<pleaceEntry>` within `<place>` mandatory 

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to
- [x] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
`<placeEntry>` within `<place>` should be mandatory

## Context

> Otherwise there could be a place with no entry and still a valid file. 

reportet by APEx project, May 2013

**Comment by karinbredenberg** [comment]
Align with EAD3? Otherwise sounds fair!

**Comment by SJagodzinski** [comment]
EAD 3 uses element `<geogname>` for encoding place names. Mandatory child element `<part>` contains the place name.

**Comment by kerstarno** [comment]
As a note from the Shared Schema team:

We are currently looking into differently named elements (and attributes) in EAC-CPF and EAD3, which essentially are meant to "do the same thing". One of the examples included in that review is `<place>` with `<placeEntry>` vs `<geogname>`. Maybe a question to ask before discussing the aspect mentioned in the title of this issue could be - why did EAC-CPF decide to use `<place>` instead of `<geogname>`? And - would the EAC-CPF team consider a change back to `<geogname>`? Potentially with `<part>` instead of `<placeEntry>`, seeing that `<part>` already exists in EAC-CPF, though is only used with `<nameEntry>` at the moment?

Just as an additional note:
In 2004, see: https://eac.staatsbibliothek-berlin.de/schema/cpf2004v01.xsd, EAC did use `<place>` with the sub-element `<part>`.

Also for reference - the definitions of all three elements in the according tag libraries:
- EAC-CPF: `<place>`: An element that provides information about a place or jurisdiction... (short definition)
- EAC-CPF: A `<place>` element is a wrapper element used to encode an index term placed within the element `<placeEntry>`. (part of long definition)
- EAC-CPF: `<placeEntry>`: An element used to encode information about the place or jurisdiction... (short definition)
- EAD3: `<geogname>`: An element for encoding place names. (short definition)
- EAD3: `<geogname>`: An element for identifying the name of a place, natural feature, or political jurisdiction (part of long definition)

**Comment by SJagodzinski** [comment]
Team discussion:
Elements eac:place/placeEntry and ead:geogname have the same meaning. 
For the purpose of standards alignment, for EAC-CPF the question would be, how to encode place names. We'd like to avoind more nested encoding like eac:place/geogname/part. 
Suggestion of shared schema team: using geogname for any placenames outside place. This way, EAC-CPF would use //geogname and //placeEntry to encode place names. Would that be userfriendly?

We are going to bring this topic to TS-EAS discussion. Decision postponed for time after SAA meeting, depending on TS-EAS decision.

**Comment by SJagodzinski** [comment]
see also [comparison report](https://docs.google.com/spreadsheets/d/13XT1lHfhEJiZ06KVeYtRu0f3ke20_9vZKoRuzKM-Ll0/edit#gid=1662057578&range=C32)

**Comment by SJagodzinski** [comment]
EAD-EAC-CPF joint meeting, 10 July 2020:

> Picking up on the questions raised during the conversation, it might be worth having a closer look at specifically the contexts of `<relation>` and `<chronitem>.` **Especially with regard to aligning how coordinates are encoded.** This could also be looking at the levels that are being compared, i.e. is it `<place>` or `<placeEntry>` that could be compared?

**Comment by SJagodzinski** [comment]
EAC-CPF Chicago meeting, 29 & 31 July 2020:

1. Go with //places/place and according child elements to encode places.
2. Rename `<placeEntry>` to `<placeName>`.
3. Add `<geographiccoordinates>` as child element of `<place>`, according to the EAD3 content model.

No discussion on availability of `<placeName>` within `<place>`, but with `<geographiccoordinates>` it would be possible to encode a place only by coordinates and not by name. This is a valid encoding for place and needs no more restrictions in the `<place>` element.

**Comment by SJagodzinski** [comment]
EAC-CPF meeting, November 2020:

Require `<place>` to have at least one of the following sub-elements: `<placeName>`, `<placeRole>`, `<address>`, `<contact>`, `<geographicCoordinates>`.
