### ISSUE TITLE
Add new content for <entityType>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#44]
Add "organizations" as new type for entities

## Creator of issue

1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com
4. in behalf of Krista Jamieson, Digital Initiatives / ​University of Alberta Archives

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

> The only options being people or corporations isn't representative. A corporation means something specific and often is not the appropriate term for charities, NGOs, associations, institutions (like schools), etc., that are also neither families nor individuals, but we are forced to use corporate body for lack of other options. Personally I would suggest "organizations" because it is vague but captures the notion of something that isn't just a person or family but is some sort of organized group, whether that be a club or a corporation.

[K. Jamieson]

## Suggested Solution

Add "organizations" as fixed value in the element //entityType

## Context

Feedback from call for comments, sent in 15 September 2017.

**Comment by wisserk** [comment]
The values available for entityType are: person, corporateBody, family. There is a semantic difference between a corporateBody and a corporation. The definition of a corporate body (from a metadata perspective as rooted in descriptive cataloging traditions) is "An organization or group of individuals with an established name that acts as a single entity" (SAA Glossary, https://www2.archivists.org/glossary/terms/c/corporate-body). This definition does not imply that all corporate bodies are corporations.

**Comment by SJagodzinski** [comment]
Comment from E. Perkes, Utah State Archives:

> I would also like <entityType> to have a local type attribute to further refine the category. Corporate Name is not specific enough when you work with government records that come from state agencies, municipalities, counties, school districts, special districts, and others.

**Comment by karinbredenberg** [comment]
We have "solved" this by using the function element and there describing the type of organization with a term and a local vocabulary and making it more granular with having one more function defined as subcategory and its term.  Easier to show, even if the code looks not as its best:
`<functions>
<function localType="mainCategory">
		<term vocabularySource="RAFGS5">stateAuthority</term>
		<citation xlink:title=" RAFGS5" xlink:type="simple">1</citation>
		<descriptiveNote>
			<p>Textual description of the organisations work</p>
		</descriptiveNote>
	</function>
	<function localType="category">
		<term vocabularySource="SCB:s kategorikoder">ADB-arbete m m</term>
		<citation xlink:title="Statistics Sweden category codes" xlink:type="simple">3250000</citation>
		<descriptiveNote>
			<p>A textual description of the work described by the code</p>
		</descriptiveNote>
	</function>
</functions>`

**Comment by fordmadox** [comment]
I think that there should be some way to extend entityType, but I'm not in favor of adding additional options to the current three.  I'm not sure if it should be the @localType attribute or something else, however.  In any event, it would be great to have standard ways in EAC that facilitate interoperability with other ontologies, controlled lists, etc.

**Comment by gerhardmueller** [comment]
"Corporate Bodies" is a general term allowing for encoding all types of organizations. It is inline with common definitions of libraries and archives: 

Definition of RDA (Resource Description and Access), 11.0: "A body is considered to be a corporate body only if it is identified by a particular name and if it acts, or may act, as a unit. A particular name consists of words that are a specific appellation rather than a general description. Typical examples of corporate bodies are associations, institutions, business firms, nonprofit enterprises, governments, government agencies, projects and programs, religious bodies, local church groups identified by the name of the church, and conferences. Ad hoc events (e.g., athletic contests, exhibitions, expeditions, fairs, and festivals) and vessels (e.g., ships and spacecraft) are considered to be corporate bodies."

Definition of ISAAR (CPF): "An organization or group of persons that is identified by a particular name and that acts, or may act, as an entity. Also includes an individual acting in a corporate capacity."

**TS-EAS EAC-CPF considers the general terms - corporate bodies, persons, families - as sufficient.**

Nevertheless, TS-EAS also discussed the possibility of encoding sub types of entities. MARC21 introduced category 075 for general types of entities (persons, corporate bodies, ...). The category is repeatable for subdivisions to describe the type of entity: https://www.loc.gov/marc/authority/ad075.html 

The German National Library published an ontology for the Integrated Authority File that distinguishes general and specifying terms (gndgen, gndspec): http://www.itsmarc.com/crs/mergedProjects/sorcecod/sorcecod/entity_type_source_codes.htm 

The terms are also available in English: https://d-nb.info/standards/elementset/gnd

**It is yet to be decided if EAC-CPF should introduce a similar approach for specifying types of entities as requested.**

**Comment by SJagodzinski** [comment]
There is a requirement to specify the provided entity types (person, family, corporate body) further.

2 proposals:
1.	Providing a best practise by using `<functions>` element, as @karinbredenberg cited, see [above](https://github.com/SAA-SDT/eac-cpf-schema/issues/44#issuecomment-348914339)
2.	Using/adding element(s) or attribute(s) to specify the entity type.

**Comment by SJagodzinski** [comment]
I see the need to specify the entity types, esp. for corporate bodys, even I didn't used it so far.

I think providing best practise by using existing elements, like `<function>` or, maybe also appropriate, `<localDescription>` makes it more complex and generates questions and uncertainties by using EAC-CPF. Defining a standard should try to avoid uncertainties and be as exact as possible.

To make the sematics of an element more specific, usually attributes are made for in XML. But we don't want to specify the elements content semantics but the entity type. Following @gerhardmueller [example](https://github.com/SAA-SDT/eac-cpf-schema/issues/44#issuecomment-422056072) in MARC21, we could use following approach:
* make `<entityType>` repeatable
* add `@type` attribute to specify, if it is the general type (person, family or corporate body) or the specific type (no limited content)
* make `<entityType>` with `@type` attribute for the general type required
* make `<entityType>` with `@type` attribute for the specifid type optional

If we would decide for this option, we need to define the  `@type` attribute. 
The existing `@localType` can be used. On the other hand, there would be limited values for the attribute, so a specific attribute would be useful and would follow current EAD 3 solutions. 
In this sense the name would be `@entityTypeType`?

**Comment by gerhardmueller** [comment]
Functions seems to be a good choice, but could be also confusing with regard to definitions provided by both the Tag Library and RiC-CM (draft v0.1) (purpose, objectives, roles). In this case it is about a specification of the entityType. I'd suggest to modify the element entityType:
```
<entityType>
     <type ontologyURI="http://d-nb.info/standards/elementset/gnd#CorporateBody">corporateBody</type>
     <subType ontologyURI="http://d-nb.info/standards/elementset/gnd#Company">Company</subType>
</entityType>
```

**Comment by ailie-s** [comment]
I agree that it would be good to be able to include local, or more specific entity types, especially within Corporate Bodies. 

We have been using 'localControl' as a workaround to include our local practices for labeling entity types, eg: 
`<localControl localType="typeOfEntity">
<term>Organisation</term>
</localControl>`

The solutions suggested by both @SJagodzinski  and @gerhardmueller would be good alternatives for expressing this data.

**Comment by eboudreau** [comment]
I agree that the three main types of entities are sufficient, and that corporateBody in this context is general enough to apply to any type of organization. I like @gerhardmueller's suggestion of including <type> and <subType> elements to the parent element <entityType>, where the available values for <type> would be person, corporateBody, and family, and the value of <subtype> would come from a controlled list of specific terms. I don't know whether <subType> would need to be repeatable, or if values would be mutually exclusive...

**Comment by regineheberlein** [comment]
FWIW, LRM defines  LRM-E6 Agent as a second-level entity, with the third-level entities
-- -- LRM-E7 Person
-- -- LRM-E8 Collective Agent
below it.

https://www.ifla.org/files/assets/cataloguing/frbr-lrm/ifla-lrm-august-2017_rev201712.pdf

"The entity person is restricted to real persons who live or are
assumed to have lived.
Strict proof of the existence of a person is not required, as long
as there is a general acceptance of their probable historicity.
However, figures generally considered fictional (for example,
Kermit the Frog), literary (for example, Miss Jane Marple) or
purely legendary (for example, the wizard Merlin) are not
instances of the entity person."

"The entity collective agent designates a wide range of named
groups of persons that bear a particular name and have the
potential of acting together as a unit. In addition to families,
commercial or corporate entities and other legally registered
bodies, the entity collective agent includes organizations and
associations, musical, artistic or performing groups,
governments, and any of their sub-units. The membership of
many types of collective agents will continue to evolve over
time.
Occasional groups and groups that are constituted as meetings,
conferences, congresses, expeditions, exhibitions, festivals, fairs,
etc., also fall under the definition of collective agent as long as
they are identified by a particular name and can act as a unit.
Joint pseudonyms or collective pseudonyms are nomens that
refer to instances of the collective agent entity as the agent
behind the identity consists of two or more persons bearing a
particular name and acting as a unit, despite having chosen to be
identified by a name culturally associated with individual
persons.
(Further discussion of individual, collective or joint pseudonyms
is found in section 5.5, Modelling of Bibliographic Identities.)
A gathering of people is considered a collective agent only when
it exhibits organizational characteristics that permit them to
perform actions that reflect agency with respect to instances of
entities of bibliographic interest (such as approving a report,
publishing the proceedings of a conference). These collective
actions may be performed by representatives selected by the
whole, rather than by all individual members acting together.
Groups of persons that do not qualify as agents (for example,
national, religious, cultural or ethnic groups, such as ItalianCanadians,
or gatherings referred to by a general descriptive
term instead of a particular name) are not instances of the entity
collective agent.
The essential distinction between a collective agent and a
gathering of people which is not an instance of the entity
collective agent, is that the name used by the instance of the
entity must be a specific name and not just a generic description
for the gathering.
Families and corporate bodies are specific types of collective
agents that may be relevant in a particular bibliographic
application."

**Comment by cannedit** [comment]
As said during the discussion: I am in favor of using @localType, provided it is used in combination with a reusable definition of these @localType values, especially since this might only be a problem for just a few institutions creating EAC-CPF files?
I used it for the Archives Portal Europe EAD3 additional finding aids implementation, see:
http://wiki.archivesportaleurope.net/index.php/EAD3_implementation_guideline#LOCALTYPEDECLARATION_.28optional_for_EAD3.2C_but_recommended_for_.28A.29FA.27s_using_this_guideline.29
see also: http://wiki.archivesportaleurope.net/index.php/EAD3_implementation_guideline#ORIGINATION_.28optional_for_EAD3.2C_but_mandatory_for_an_AFA.29
and: http://wiki.archivesportaleurope.net/index.php/EAD3_apetypes

**Comment by wisserk** [comment]
What about:

<entityType>
<localEntityType>
??

**Comment by SJagodzinski** [comment]
## Discussion: ##
TS-EAS EAC-CPF **agrees on the requirement of an high-level and non-repeatable element for the entity type** with 3 terms corporate bodies, persons, families .

The team also **see the requirement to encode local or more specific entity types** in addition, even there is a risk to create useless data by entering, e.g. entity type: corporate body, local entity type: person. But other standards and data structures are using this kind of entity type definition, too, so mapping will be much more feasible. 

Discussion about the exact encoding: Using `<function>` to describe the entity type would be correct. But in this case identity information would be encoded in the description information part. On the other hand, this solution would need more explanation and information, e.g. in the Tag Library, as best practise.

## Decision: ##
- Having one `<entityTypeDeclaration>` as wrapper element - being mandatory and not repeatable.

- Having one `<entityType>` with 3 terms (corporate bodies, persons, families) as child of `<entityTypeDeclaration>` – being mandatory and not repeatable.

- Having `<localEntityType>` with any text content as child of `<entityTypeDeclaration>` - being optional and repeatable.

- Both child elements need `@localType` to include references, e.g. to an ontology.

## Example encoding: ##
`<entityTypeDeclaration>
<entityType localType="http://d-nb.info/standards/elementset/gnd#CorporateBody">corporateBody</entityType>
<localEntityType localType="http://d-nb.info/standards/elementset/gnd#Company">Company</localEntityType>
</entityTypeDeclaration>`

**Comment by SJagodzinski** [comment]
EAC-CPF team virt meeting 3 July 2020:

The entity type has to be a mandatory element with defined values, i.e. there will be only 3 entity types. To encode more specific information on an entity type, the usage of an additional descriptive entity type element is needed. Following the approach in EAS for repeatable elements so far, usage of a plural wrapper element for `<otherEntityType>` is convincing. 

c.f. #141 , #116
