### ISSUE TITLE
<biogHist/>: please allow <head/>

### ISSUE THREAD

**Issue by cannedit** [SAA-SDT/eac-cpf-schema#51]
## Creator of issue

1. Wim van Dongen
2. TS-EAS, EAC-CPF subgroup
3. wim.van.dongen@nationaalarchief.nl or wimvdongen@gmail.com or cannedit@gmail.com
4.

## The issue relates to

- [X] EAC-CPF schema issue
- [X] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

Please allow "head" within "biogHist"; my use case for this: working on extracting information on persons from our (APE) EAD3 additional finding aid implementation towards EAC-CPF, I would like to populate EAC-CPF’s "biogHist" with multiple "p"’s and would then like to be able to make some sort of chapter-like subdivision; at the moment, I can only do that using "abstract" which is not really meant for this of course, so I would like to use a "head" for that (just like in EAD2002 and EAD3); see the code and display example attached.
![eac-cpf_bioghist-abstract_vs_bioghist-head_code](https://user-images.githubusercontent.com/22167327/34610304-7a15c0b6-f218-11e7-934b-0ac034f29018.png)
![eac-cpf_bioghist-abstract_vs_bioghist-head_display](https://user-images.githubusercontent.com/22167327/34610305-7a35b240-f218-11e7-9b2b-6ed1ce96ae20.png)

**Comment by regineheberlein** [comment]
I would argue against doing this. While I concede that allowing biogHist/head would reconcile CPF with EAD3, it feels very beholden to a narrative legacy of archival description, as opposed to a data-centric approach. As such, it feels like a step back, and I would rather see head/ removed from EAD3 than see it used as the precedent for allowing it in CPF.

(In the example provided (which seems fairly structured), biogHist/chronlist in lieu of biogHist/p might be a workable approach?)

**Comment by cannedit** [comment]
I considered biogHist/chronlist, but that is imho way to redundant and although the data as provided in the example file might be suitable for this, the information in other files I would like to treat like this is not; besides if you take a thorough look at the content of the example file, then using biogHist/chronlist would entail a lot of editorial work on these data and they are meant to be dumped down from huge databases, so that's not really an option.
As for the reason for disapproving this: what's against a narrative legacy of archival description? If you look at the presentation of data in SNAC for instance, you might argue the contrary: that some of these vast amounts of information would be more readable when some 'breaks' would have been used in the form of a 'head': check for instance: http://snaccooperative.org/view/5402727 and http://snaccooperative.org/view/28503331.

**Comment by regineheberlein** [comment]
It's a conceptual problem, which translates into a pragmatic one. 

Conceptually, biogHist/ is a property of the CPF entity. The purpose of making the XML element repeatable is not to break it up into narrative chapters all pertaining, as fragments, to the same entity, but to allow for describing complex entities or for giving narrative as well as structured description side by side. (Note that I find the repeatability of biogHist/ for the latter purpose questionable, but let's take it as a given for the moment.) So conceptually, a simple CPF entity should have a single biogHist note property. 

I assume you're requesting head/ based on EAD3. However, just as abstract/ doesn't repeat in biogHist/, neither does head/ repeat in bioghist/ in EAD3 (both for good reason: because one note can't have more than one head or more than one abstract). So what happens when you use abstract/, and what would likewise happen if you used a hypothetical head/ modeled on EAD3, to encode a chapter heading is that you are forced to repeat biogHist/, thereby creating multiple biogHist/ fragments for the same entity. I believe that to be a conceptual misuse of biogHist/: in effect, you're coding for display. 

I don't see, therefore, what would be gained by allowing head/ here--you need it to code for display, but you're already coding for display by using abstract/. By using head/ instead you'd get the exact same display but conceptually legitimize the biogHist/ fragment.

One more thought about very long biogHist's, which are the source of your frustration (and I sympathize--wrangling data you didn't create is a headache, as all of us can attest!). My view is that the note in a CPF record, just like in any other bibliographic authority record, is no place to wax verbose. Nevertheless, they often do, which presents display as well as actionability problems. So in a way I think we're discussing the wrong problem here (how to handle very long bio notes) when we might instead consider imposing a character limit on the biogHist note to begin with. In fact, I think that's already on the horizon with RiC.

On a more general note, I think whatever changes are made to any EAD schema, including the CPF one, should move in the direction of aligning it with the RiC data model. If you look at the RiC Agent properties, you'll see property P-35, a concise text note--my emphasis on "concise". Beyond that, Agent enters into relationships with other *entities* including Occupation, Position, Function, Activity.

**Comment by MicheleCombs** [comment]
If the purpose of EAC-CPF is to provide context regarding a C, P, or F, it seems to me to be counterproductive to limit the length.   The decision of how long a bioghist needs to be to provide proper context should surely be left to the individual creators?  And if it is long, why would we not allow them to create subheadings to assist the end user in reading/interpreting?

**Comment by cannedit** [comment]
Yes I am guilty of being a practical guy and I am not much of a conceptual theorist (no offense intended) and I don't see any harm in coding for display either, because after all - at least imho - the real purpose of standardization is to be able to present information from a variety of sources in the best possible and most user friendly way to the audience. But forget it, I hereby withdraw my request. I have made another arrangement for my EAD3 to EAC-CPF mapping on this point anyway.

**Comment by regineheberlein** [comment]
@MicheleCombs This is going off-topic from the original issue, but you bring up an interesting question--what is "proper context," or rather, what is "Context," as a technical term in archival description? It's surely distinct from the casual word "context" as anything that adds information (and hence by definition is potentially boundless, as you point out). Personally, I would like to see a more rigorous definition that frames context as information both external to the resource being described and necessary to support user functions. The latter, to me, also suggests that context should be expressed as structured data, rather than blobs of text, to the extent possible.

**Comment by wisserk** [comment]
I envision the bioghist (and a few other elements) to be informal descriptive elements, meaning that they are not intended to be leveraged the way other data centric elements (more formal descriptive elements with a built in structure) are. What is nice about the collected elements in the <description> area is the combination of both formal and informal elements. Narrative descriptions have their value.

**Comment by SJagodzinski** [comment]
### Results of team discussion:

The schema change is not needed anymore by the creator and as it turned out to be a comprehensive discussion about ho to encode data and content in a schema, the topic is forwarded to the revision (phase 2).
Wim agrees to share his workaround.

**Comment by SJagodzinski** [comment]
see also [comparison report](https://docs.google.com/spreadsheets/d/13XT1lHfhEJiZ06KVeYtRu0f3ke20_9vZKoRuzKM-Ll0/edit#gid=1548633886&range=C79)

**Comment by SJagodzinski** [comment]
EAC-CPF revision discussion and [December 2020 meeting](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/meeting-minutes/2020/20201204_EAC-CPF_minutes.pdf) outcome:

Add `<head>` as child element to `<biogHist>`, `<generalContext>`, `<list>`, and `<structureOrGenealogy>`. 
The element is mainly needed to allow more clarity in multi-level lists specifically.
