### ISSUE TITLE
<maintenanceStatus>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#84]
## Maintenance Status

- remove the element from EAC-CPF
- **add new mandatory attribute** `@maintenanceStatus` with restricted values (revised, deleted, new, deletedsplit, deletedmerged, deletedreplaced, cancelled, derived) to `<control>` instead

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[`<maintenanceStatus>`: element content should become attribute value #5](https://github.com/SAA-SDT/eac-cpf-schema/issues/5)
`<agentType>` #94 

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@lang` - Optional
`@script` - Optional

**May contain**: [text]

## Context

An element used to indicate current drafting status of the EAC-CPF instance.

Revising EAC-CPF, the element will be removed and an attribute <control @maintenanceStatus> will indicate the current drafting status of the EAC-CPF instance.

## Solution documentation

- remove from Tag Library

**Comment by SJagodzinski** [comment]
EAC-CPF Berlin meeting, 11 March 2020:

Use `<maintenancestatus>` as an empty element without text or other content with a required attribute `@value` with limited values and without language attributes. This element is mandatory and not repeatable.

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary**: A required child element of `<control>` that records the current version status of the EAC-CPF instance.
**May contain**: [empty]
**May occur within**: `<control>`
**Description and Usage**:  Use  `<maintenanceStatus>` to indicate the current drafting status of an  EAC-CPF instance. The current version status should always be updated   whenever an EAC-CPF instance is modified (as recorded in   `<maintenanceHistory>`). 
The current maintenance status must always be reflected in the required `@value` attribute. The element itself must remain empty.
**Attributes**:
`@audience` - optional (values limited to: external, internal)
`@id` - optional
`@value` - required (values limited to: revised, deleted, new, deletedsplit, deletedmerged, deletedreplaced, cancelled, derived)
**Attribute Usage**: Use the value of the `@value` attribute to record the status of the EAC-CPF instance.
Upon creation, record the value as "new."
On revision, change the value to "revised."
Because it is important to be clear about what has happened to instances, particularly when sharing and making links between them, a number of status values are available for records that are no longer current: "deleted", "deltedsplit", "deltedmerged", "deletedreplaced" or "cancelled".
A "derived" value is available to indicate that the record was derived from another descriptive system.
**Availability**: Required, not repeatable

**Comment by SJagodzinski** [comment]
Outcome EAC-CPF September 2020 meeting:

We will not have control type elements anymore; we will move them to attributes to their parent elements. 
We have decided to put the elements `<maintenanceStatus>` and `<publicationStatus>` as attributes into `<control>`.

**Comment by kerstarno** [comment]
Schema team, schema tests: 

I've tested the draft XSD and RNG schemas for EAC-CPF 2.0 with regard to "maintenanceStatus". There is no option anymore to include an element `<maintenanceStatus>` anywhere within `<control>`, but the attribute `@maintenanceStatus` is now being made available instead for `<control>`. All existing values of the element have been moved to the attribute. 

While this works fine function-wise, the spelling needs to be corrected for three possible values: both, XSD and RNG schema, currently spell "deleted-merged", "deleted-replaced" and "deleted-split", while this should follow the agreed camelCase spelling. 

An according pull request that fixes these spellings has been created: https://github.com/SAA-SDT/eac-cpf-schema/pull/163

**Comment by kerstarno** [comment]
Rechecked after the merge of the pull request #163 and can confirm that the spelling for the attribute values now works fine.

**Comment by fordmadox** [comment]
Given that our other attribute values in EAD/C use the kebab-case convention (some of which are taken from CSS according to EAD3), what would everyone think about using different naming schemas for tag names vs. attribute values?  I'm still in favor of kebab-case across the board :smile:, but I'd really rather not have attribute values like "decimalLeadingZero" in EAS when "decimal-leading-zero" is the value from CSS.

**Comment by kerstarno** [comment]
Might only be me, but I'd rather have the same approach in all aspects, from element and attribute tags to values. Also, the only attribute I could find so far that uses kebab-case is `@numeration`, where it might the question if that actually will still exist in this way in a new version of EAD, plus "in-depth" for `@dsctype`, and some values for `@cpfRelationType`, which  won't exist as such in the new version anymore ("hierarchical-parent", "hierarchical-child", "temporal-earlier", "temporal-later").

**Comment by SJagodzinski** [comment]
@fordmadox : I agree with Kerstin here. If you can find a range of values used in CSS/HTML I'll be convincible.
