### ISSUE TITLE
<agencyName>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#88]
## Agency name
- add attributes
`@audience`
`@scriptOfElement`
`@valueURI`
`@vocabularySource`
`@vocabularySourceURI` 
- keep elements name and definition

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@lang` - Optional
`@localtype` - Optional
`@script` - Optional

## Context
The name or names of the institution or service responsible for the creation, maintenance, and/or dissemination of the EAC-CPF instance.

**May contain**: [text]
**May occur within**: `<maintenanceAgency>`
**Attributes**: `@xml:id`, `@xml:lang` - all optional
**Availability**: Mandatory, Repeatable

## Solution documentation
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain**: [text]
**May occur within**: `<maintenanceAgency>`
**Attributes**:
`@audience` - optional (values limited to: external, internal)
`@id` - optional
`@languageOfElement`- optional
`@scriptOfElement` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Availability**: Required, repeatable

- New or other example needed?
- Topic for Best Practise Guide?

## Example encoding
```
<maintenanceAgency>
  <agencyCode status="authorized">agency code</agencyCode>
  <agencyName audience="external" id="agencyName1" languageOfElement="eng" scriptOfElement="lat" valueURI="agencyNameURI" vocabularySource="VIAF" vocabularySourceURI="VIAFURI" target="agencycode1">agency name</agencyName>
</maintenanceAgency>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A required child element of `<maintenanceAgency>` that provides the name of the institution or service responsible for the creation, maintenance, and/or dissemination of the EAC-CPF instance.
**May contain:** [text]
**May occur within:** maintenanceAgency
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@id` - optional
`@languageOfElement`- optional
`@scriptOfElement` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Description and Usage:**
Use `<agencyName>` to record the name of the institution or service responsible for the creation, maintenance, and/or dissemination of the EAC-CPF instance. Examples include the repository name or the name of an aggregation service.
It is recommended to use the form of the agency name that is authorized by an appropriate national or international agency or service.
`<agencyName>` may be repeated in order to provide the name of the institution or service responsible for the EAC-CPF instance in multiple languages. If `<agencyName>` is repeated it is recommended to indicate the language of each name using `@languageOfElement`.
**Availability:** Required, repeatable

**Comment by karinbredenberg** [comment]
Test of element agencyName:
May occur within: maintenanceAgency 1..n **Ok in both schemas**
Contains text  **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement- optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@valueURI - optional **Ok in both schemas**
@vocabularySource - optional **Ok in both schemas**
@vocabularySourceURI - optional **Ok in both schemas**

**Result**: Element ready

**Comment by kerstarno** [comment]
@SJagodzinski and @fordmadox for information:

The most recent EAC Team meeting discussed the question of potentially requiring content for those elements that are currently mandatory for a minimum EAC instance. `<agencyName>` is one of these. The Schema Team followed up on this during their meeting today and suggest to make `<agencyName>` optional. Seeing that it currently does not require to have content, we do not foresee any issues with regard to moving from EAC-CPF 1.0 to EAC-CPF 2.0 in this context. 

For background see also: https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/schemas-subteam/working-documents/20210108_ContentRequirement_MandatoryElements.pdf

**Comment by kerstarno** [comment]
For now, the suggested change has been implemented in the draft schema. Pending final confirmation. (See also in the context of #95 and #93.)

**Comment by SJagodzinski** [comment]
Having `<agencyName>` optional can result in an empty element `<maintenaceAgency>`. That's even less useful. 

I suggest to provide a choice having either `<agencyName>` or `<agencyCode>` available. If only one of the elements is available, it has to have content.

**Comment by kerstarno** [comment]
> Having `<agencyName>` optional can result in an empty element `<maintenaceAgency>`. That's even less useful.

Which is why the suggestion would have been to also make `<maintenanceAgency>` optional.

> I suggest to provide a choice having either `<agencyName>` or `<agencyCode>` available. If only one of the elements is available, it has to have content.

@fordmadox - this will need redoing in the schema. Please let me know, when you've had time to implement the change, and I'll re-test.

**Comment by kerstarno** [comment]
With the confirmation of `<maintenanceAgency>` in #86, this element is ready schema-wise as well.
