### ISSUE TITLE
<eventDateTime>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#93]
## Maintenance Event Type
- add attributes
`@audience`
`@scriptOfElement`
- keep element name and definition

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@script` - Optional

## Context
The date and time of a maintenance event for the EAC-CPF instance.

**May contain**: [text]
**May occur within**: <maintenanceEvent>
**Attributes:** `@standardDateTime`, `@xml:id`, `@xml:lang` - all optional
**Availability:** Mandatory, Non-repeatable

## Solution documentation
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain**: [text]
**May occur within**: <maintenanceEvent>
**Attributes:** 
`@audience` - optional (values limited to: external, internal)
`@id` - optional 
`@languageOfElement` - optional 
`@scriptOfElement` - optional 
`@standardDateTime` - optional
**Availability:** Required, not repeatable

- New or other example needed?

## Example encoding
```
<control>
 <recordId>records identifier</recordId>
 <maintenanceAgency> [...] </maintenanceAgency> 
 <maintenanceHistory>
  <maintenanceEvent>
   <eventDateTime audience="external" id="eventdatetime1" languageOfElement="de" scriptOfElement="lat" standardDateTime="2020-07-01T13:01:48">01.07.2020</eventDateTime>
   <agent>agent name</agent>
  </maintenanceEvent>
 </maintenanceHistory>
</control>
```

**Comment by ailie-s** [comment]
Tag Library Text: 

**Summary:** A required child element of `<maintenanceEvent>` that records the date and time of a specific maintenance action for an EAC-CPF instance.
**May Contain:** [text]
**May occur within:** `<maintenanceEvent>`
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@id `- optional
`@languageOfElement` - optional
`@scriptOfElement` - optional
`@standardDateTime `- optional
**Description and Usage:**
A required child element of `<maintenanceEvent>`, `<eventDateTime>` is for recording the date and time that a maintenance event occurred. Examples of maintenance events include the creation, update, revision, or other modification to an EAC-CPF instance.
The date and time may be captured in natural language in the element.
**Attribute Usage:** Use `@standardDateTime` to provide a machine-processable expression of the date or date and time, formulated according to the ISO 8601 standard.
**Availability:** Required, not repeatable

**Comment by karinbredenberg** [comment]
Element eventDateTime tested:

May occur within: <maintenanceEvent> 1..1 **Ok in both schemas**
May Contain: [text] **Empty element in both schemas**
@audience - optional (values limited to: external, internal)  **Ok in both schemas**
@id - optional  **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@standardDateTime - optional **Ok in both schemas**

**Result**: Element cant hold text.

**Comment by fordmadox** [comment]
Oh, I don't like that it can hold text (since it's in the control section), but I'll update this later today in the development branch to fix that :smile:

**Comment by fordmadox** [comment]
@karinbredenberg just a note that I just patched this.  see https://github.com/SAA-SDT/eac-cpf-schema/commit/62d33a540e12a1363fbb7adbc8069a2ea41902bf.  thanks!

**Comment by karinbredenberg** [comment]
Retested. Element now ready.

**Comment by kerstarno** [comment]
@SJagodzinski and @fordmadox for information:

The most recent EAC Team meeting discussed the question of potentially requiring content for those elements that are currently mandatory for a minimum EAC instance. `<eventDateTime>` is one of these. The Schema Team followed up on this during their meeting today and suggest to use the same approach for `<eventDateTime>` as is currently foreseen for `<entityType>`, i.e. keeping the element as mandatory, but also requiring the attribute `@standardDateTime`. Furthermore, `<eventDateTime>` would then not allow for content anymore. 

When moving from EAC-CPF 1.0 to EAC-CPF 2.0 in this context, there could be a check on the current content of the element, which - provided that it actually is a date - is expected to be convertible to an ISO standard like date format for `@standardDateTime`. In case the element has been left empty in an EAC-CPF 1.0 file, we could consider using a default value such as "0000-01-01T00:00:00". 

For background see also: https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/schemas-subteam/working-documents/20210108_ContentRequirement_MandatoryElements.pdf

**Comment by kerstarno** [comment]
If we do not make `@standardDateTime` mandatory and do not restrict `<eventDateTime>` from having text (note that - contrary to other aspects in this context - the suggested change has not been implemented yet in the draft schema), do we then require the element to have content instead? Do we do something similar as has now been implemented (for testing) with regard to `<part>` (see #133), i.e. requiring that at least one non-whitespace character must be present?

What would be the risk/problem foreseen in the suggested change?

**Comment by SJagodzinski** [comment]
> The most recent EAC Team meeting discussed the question of potentially requiring content for those elements that are currently mandatory for a minimum EAC instance. `<eventDateTime>` is one of these. The Schema Team followed up on this during their meeting today and suggest to use the same approach for `<eventDateTime>` as is currently foreseen for `<entityType>`, i.e. keeping the element as mandatory, but also requiring the attribute `@standardDateTime`. Furthermore, `<eventDateTime>` would then not allow for content anymore.

This solution forces users for automatic creation of EAC-CPF files or at least of the `@standardDateTime` value. This produces new hurdles which we want to avoid by simplifying the schema. 

The element `<eventDateTime>` will not require the attribute `@standardDateTime` and will allow text.

**Comment by kerstarno** [comment]
Ok. Fair enough - even though, personally, I wouldn't see it as too much of a hurdle to type `<eventDateTime standardDateTime="2021"/>` instead of `<eventDateTime>2021</eventDateTime>`.

Still pending question, @SJagodzinski , which might require adaptation of the schema (@fordmadox): do we require the element to have content? I.e. do we do something similar as has now been implemented (for testing) with regard to <part> (see #133), i.e. requiring that at least one non-whitespace character must be present? 

Update: requiring content in `<eventDateTime>` would also be in line with the approaches to `<agent>` and the duo `<agencyCode>` and `<agencyName>` which all aim to ensure that at least some information is provided.

**Comment by fordmadox** [comment]
I don't think we should require text in this element, and @SJagodzinski mentioned that it should "allow" text, not "require" text, so I think that's the intent?  

The schema does require the element right now, but of course it can be empty since we haven't added any additional constraints.  In my mind, we should either eliminate this element and move the required attribute up to the parent element  (which is an option that I kind of like since it means there is only one way to assign such a date, but this is also administrative metadata, so I don't know why we would need to be so strict), or we should keep the base schema as it is and add a rule in the Schematron file that will require content either in the attribute OR the text node (which I think might be the best method for now, since it would not incur potential data loss during a migration from EAC 1 to 2.)

@SJagodzinski, @kerstarno  :  would it be okay to try to enforce some value via the Schematron rules?  

And just so that I'm clear, we are suggesting that all three of the following values should be valid, right?:

```
<eventDateTime standardDateTime="2021"/>
```

```
<eventDateTime standardDateTime="2012-01-13T04:47:56">13 janvier 2012 04:47:56 PST</eventDateTime>
```

```
<eventDateTime languageOfElement="eng">Yesterday</eventDateTime>
```

Due to the last example, I like the attribute-only approach (e.g. `maintenanceEvent/@eventDateTime`), but since this is administrative metadata, I don't know if there is a real use case for enforcing such uniformity.

**Comment by kerstarno** [comment]
Just to clarify: `@standardDateTime`is NOT required at the moment. Not in EAC-CPF 1.0, and currently not in the draft for EAC-CPF 2.0. However, `<eventDateTime>` is required, though not asking for text, essentially meaning that one could also have `<eventDateTime/>` in a valid EAC-CPF 1.0 file.

Starting with a conversation about `<recordId>` (which is required, but also requires content), Schema Team was tasked with looking at all elements that are currently required for a minimal EAC-CPF instance, but do not require content, and to come up with suggestions on how to deal with these. 

After review, we found that this would affect the following elements:
- `<agent>` which in itself does not require content, but requires the attribute `@agentType` in EAC-CPF 2.0 (which was a required element in EAC-CPF 1.0); following the conversation in #95, it is considered useful enough to have the attribute's value saying "human", "machine", or "unknown", which is why the element would still be allowed to remain empty
- `<agencyName>` which, following the conversation in #88, is now suggested to be treated together with `<agencyCode>`, requiring at least one of these two to be present and - in case only one is present - requiring content
- `<part>` with `<nameEntry>` which in #133 has now been confirmed to require at least one non-whitespace character
- `<eventDateTime>` for which the possibility to make it optional was set aside by the Schema Team, as - contrary to `<agent>` - it was considered to be easier and more usual to provide an `<eventDateTime>` (even with only a year, and no matter whether done manually or via an export or other script); the suggestion the Schema Team consequently set out, keeping `<eventDateTime>` required, but not allowing text anymore and making `@standardDateTime` mandatory instead, has now been dismissed, meaning that `<eventDateTime>` would now be the only remaining mandatory element that can be completely empty
  - I would hence support an approach that either requires `<eventDateTime>` to have content OR to use `@standardDateTime` with an according normalised value
  
So, yes, all of the below should be valid:
```
<eventDateTime standardDateTime="2021"/>
```

```
<eventDateTime standardDateTime="2012-01-13T04:47:56">13 janvier 2012 04:47:56 PST</eventDateTime>
```

```
<eventDateTime languageOfElement="eng">Yesterday</eventDateTime>
```
but the following should not be anymore:
```
<eventDateTime/>
```

As for the idea to remove `<eventDateTime>` completely and to instead introduce an attribute `@eventDateTime` with `<maintenanceEvent>`: while this would be an option in theory, I understand @SJagodzinski's concerns against making `@standardDateTime` mandatory in that way that we should avoid requiring users to only provide normalised dates. And I would assume, an `@eventDateTime` attribute would have the same definition as `standardDateTime` has at the moment, right? So, same hurdle here.

**Comment by fordmadox** [comment]
That type of variability within the same element will have to be enforced with a Schematron rule, I suspect, so I will add that to the list.

**Comment by SJagodzinski** [comment]
@fordmadox 
> I don't think we should require text in this element, and @SJagodzinski mentioned that it should "allow" text, not "require" text, so I think that's the intent?

Right

> The schema does require the element right now, but of course it can be empty since we haven't added any additional constraints. In my mind, we should either eliminate this element and move the required attribute up to the parent element (which is an option that I kind of like since it means there is only one way to assign such a date, but this is also administrative metadata, so I don't know why we would need to be so strict), or we should keep the base schema as it is and add a rule in the Schematron file that will require content either in the attribute OR the text node (which I think might be the best method for now, since it would not incur potential data loss during a migration from EAC 1 to 2.)
> 
> @SJagodzinski, @kerstarno : would it be okay to try to enforce some value via the Schematron rules?

Yes, it would be ok.

> And just so that I'm clear, we are suggesting that all three of the following values should be valid, right?

Yes, they should be valid.

> [...] I like the attribute-only approach (e.g. maintenanceEvent/@eventDateTime), but since this is administrative metadata, I don't know if there is a real use case for enforcing such uniformity.

Here I agree with @kerstarno. We would force users to provide standardised dates.

**Comment by kerstarno** [comment]
Given that the change suggested by the Schema Team had not yet been implemented in the draft schema and seeing that we are at a point where we keep the element `<eventDateTime>` and its attribute `@standardDateTime` as they are with the main addition being a check via Schematron that either the element contains text or uses the attribute with an appropriate value, the element is ready.
