### ISSUE TITLE
<languageDeclaration>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#97]
## Language Declaration
- add **attributes**
`@audience`
`@languageCode`
`@languageOfElement`
`@scriptCode`
`@scriptOfElement` 
- remove sub elements `<language>` and `<script>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@script` - Optional

## Context
The declaration of the languages and scripts used in the EAC-CPF instance.

**May contain**: `descriptiveNote`, `language`, `script`
**May occur within**: `control`
**Attributes:** `@xml:id`, `@xml:lang` - all optional
**Availability:** Optional, Repeatable

## Solution documentation
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain**: `descriptiveNote`
**May occur within**: `control`
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@id` - optional 
`@languageCode` - mandatory
`@languageOfElement` - optional
`@scriptCode` - optional 
`@scriptOfElement` - optional
**Availability:** Optional, repeatable

- New or other example needed
- Topic for Best Practise Guide

## Example encoding
```
<control>
 <recordId>records identifier</recordId>
 <maintenanceStatus value="new"/>
 <publicationStatus value="inprocess"/>
 <maintenanceAgency>
  [...]
 </maintenanceAgency>
 <languageDeclaration audience="external" id="languageDeclaration1" languageOfElement="eng" languageCode="eng" scriptOfElement="lat" scriptCode="lat">
  <descriptiveNote>
   <p>note for language declaration</p>
  </descriptiveNote>
 </languageDeclaration>
 <maintenanceHistory>
  [...]
 </maintenanceHistory>
</control>
```

**Comment by SJagodzinski** [comment]
Decision EAC meeting, 24 April 2020:

1. Remove elements `<language>` and `<writingsystem>` (fka `<script>`) from `<languagedeclaration>` and encode this information via attributes. 
2. Keep the optional element `<descriptivenote>.`

**Comment by fordmadox** [comment]
Should this be ```@languageOfElement``` instead of ```@languageCode```?  If so, I wonder if we shouldn't go with a name like ```@languageOfDescription``` (since we're not using xml:lang, and if we need a separate section in control to list the language(s) of the finding aid, well, it just seems odd)?  

Anyhow, I'm adding ```@languagecode``` and ```@scriptcode``` for now, but the way this is handled in EAD3 (using lang/langcode for the same purpose in different places) seems confusing... or I'm just confused... but that still would indicate that it's confusing, I think.

**Comment by kerstarno** [comment]
As I'd see it, `<languageDeclaration>` is used to define the dominant language and writing system used for the descriptive information within an EAS instance, while `@languageOfElement` and `@scriptOfElement` are used more specifically for certain elements that might - or might not - have a different language or writing system. 

I would suspect that in most cases, implementers of the EAS will only give one language and writing system in the `<control>` section, even if their descriptions include other languages or scripts as well. E.g. when I have a finding aid that's predominantly in English, but includes some descriptive parts in French and German, though only marginally, I might not bother listing all three languages in the `<control>` section, but rather make the distinction in the places of the description where it's necessary. That being said, even if only one language is used within an EAS instance, it might still make sense to have the `@languageOfElement` and `@scriptOfElement` repeatedly given in each element if you consider sharing data openly, which might also mean that users cherry pick only parts of the original EAS instance (and might not include the `<control>` section in that).

Personally, I would find `@languageOfDescription` as an attribute next to `@languageOfElement` more confusing than `@languageCode`, which - to me - is similar to e.g. `<agencyCode>` in the `<control>` section. Also, `@lang(uageOfElement)` and `@lang(uage)Code` are not used for the same purpose, they only make use of the same list of possible values - following the ISO standards.

**Comment by MicheleCombs** [comment]
...it might still make sense to have the @languageOfElement and @scriptOfElement repeatedly given in each element if you consider sharing data openly, which might also mean that users cherry pick only parts of the original EAS instance (and might not include the <control> section in that)...


I'm curious - do we have any cases, examples, evidence -- even anecdotal -- that people are in fact doing this?

Michele

*******
Michele Combs
Lead Archivist, Special Collections Research Center
Syracuse University
315-443-2081
mrrothen@syr.edu

**Comment by kerstarno** [comment]
Not cherry picking to full extent, but when Archives Portal Europe (domain-specific, EAD 2002 as the main format) provides data to Europeana (cross-domain, EDM as the main format) we convert the EAD files to EDM by concentrating only on those parts that include links to digital objects (as that's Europeana's main focus). We have a few aspects that we cover via inheriting information from higher levels (e.g. for `<origination>`, which might be only on `<archdesc>` level, but not with every `<c>` element), but essentially a lot is stripped away from the EAD files in this process and the `<control>` section (or, in our case, the `<eadheader>`) is one of the parts of the EAD files that does not stay in EDM. 

And, with regard to language attribution for specific elements such as title information or a scope and content note or the name of the creator, we currently add this via an additional function in the EDM conversion process (again due to the fact, that Archives Portal Europe does not use EAD3, hence only includes a `<langusage>` element to draw conclusions from).

-------

Also in Archives Portal Europe, we are currently working on an extension to our users' area, which would allow users to create and publish their own "finding aids" or "collections" based on their research topic and combining information from several finding aids of potentially different institutions - provided those institutions have agreed to share their descriptive metadata in such ways. I.e. it would be possible to combine information from the `<c>` elements of one EAD file with `<c>` elements of others and to ignore most of the other elements of the EAD files. 

-------

Last, to give an example of the EAC-CPF context, I'd think you could see SNAC's combination of different `<biogHist>`-s from different contributors as a similar case. There you'd only preserve the `<biogHist>` elements of the constituent original EAC-CPF files, but not much more (at least if I remember SNAC's processes correctly).

**Comment by MicheleCombs** [comment]
Very cool!!  Thanks :)

Michele

**Comment by fordmadox** [comment]
For EAC, the multiple biogHists is a great example.  With that use case, I'd personally want to indicate the language at that level, not within the control section.   Doing this in a repeatable/parallel way within control also goes against how things generally work in XML/HTML, where you declare the primary language at the document element and only supply a new one when the language of the encoding switches.  

Also, just noting this here for now: 

> It is not recommended to use your own attribute or element to specify the language of the content. The xml:lang attribute is supported by various XML technologies such as XPath and XSLT (e.g. the lang() function). Using something different would diminish the interoperability of your documents and reduce your ability to take advantage of some XML applications.
(from https://www.w3.org/TR/xml-i18n-bp/#idIntro)

I know there is a desire not to use external namespaces, and I know that EAD3 decided not to introduce xml:lang, but it seems like we're doing a lot of work to avoid using xml:lang when xml:lang was already designed to do this work 😄.

**Comment by kerstarno** [comment]
If I remember correctly from our conversation in Berlin the main "issue" with `@xml:lang` is that this doesn't come with any additional definition or declaration. I.e. using `@xml:lang` does not relieve us of deciding which type of values we want to allow and whether we'd define a specific set of values within the EAS (as it was done in EAD 2002 - just mentioning for reference, not saying we should go back to that) or would point to other standards such as the various ISO 639 versions or the IANA registry in order to do so. 

I've tried finding out if using `@xml:lang` would have an advantage e.g. when it comes to big (commercial) search engines and rankings by language preference, but in the end it's not the EAS XML files that would be searched but some other representation of these, which might - or might not - make use of `@xml:lang` for themselves. Maybe anyone else could shed some more light on this?

I'm also not convinced 100% by the interoperability argument in this case, seeing that e.g. HTML uses `@lang` instead of `@xml:lang` and that other standards like MODS and MADS use both next to each other. TEI uses `@xml:lang` but also uses the other XML attributes, METS and PREMIS seem to have no language attribution (at least I couldn't find any apart from the one used for the `<xsd:documentation>` elements) and I wasn't quite sure about MARC21 (sorry, not using it myself and never have), where the MARCXML Illustrated (https://www.loc.gov/standards/marcxml/xml/spy/spy.html) lists the attribute group "xmlGlobalAttributes", though these don't seem to appear in any of the elements, while the MARCXML Schema (https://www.loc.gov/standards/marcxml/schema/MARC21slim.xsd) does not list a language attribute.

I would therefore still argue for sticking to the decision to not introduce the XML namespace in EAD and to remove it from EAC-CPF, if it doesn't bring us a specific advantage - and especially if we do not use all attributes from XML namespace.

**Comment by fordmadox** [comment]
I'd like to create a branch that reinstates this feature just as a proof of concept, since I think it will be easier to demonstrate benefits that way.  

For just one example, it would mean "one way of doing something" moving forward for EAD/C, rather than providing multiple options (e.g. you can use this standard to indicate the language of the XML, or this standard, or this, etc.).  It would also mean that you can use some of the same tools and techniques (including built-in functions in standard toolsets, like XPath) when working with heterogenous documents, like TEI, DocBook, etc., without having to read up on the EAS specification to figure out how EAS has decided to specify the language of description.  Further, it makes it much easier to repurpose the data in a linked data environment (e.g. RDF also takes advantage of xsd:language, so why make it more difficult to move the data between serializations, systems, etc.?).

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional child element of `<control>` that indicates the language and script in which an EAC-CPF instance is written.
**May contain:** `<descriptiveNote>` (0..1)
**May occur within:** `<control>`
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@id `- optional
`@languageCode` - required
`@languageOfElement` - optional
`@scriptCode` - optional
`@scriptOfElement` - optional
**Description and Usage:**
An optional child element of `<control>` that declares the languages and scripts in which an EAC-CPF instance is written in the `@languageCode` and `@scriptCode` attributes. Any comments about the languages and scripts in which the EAC-CPF instance is written may be included in the optional `<descriptiveNote>` element.
**Attribute Usage:**
The required `@languageCode` attribute must be used to encode a valid code from ISO 639-2b.
The `@scriptCode` attribute can be used to encode a valid code from ISO 15924.
**Availability:** Optional, repeatable

**Comment by karinbredenberg** [comment]
Test of element languageDeclaration:
May occur within: <control> 0..n **Ok in both schemas**
May contain: <descriptiveNote> (0..1) **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageCode - required **Ok in both schemas**
@languageOfElement - optional  **Missing in both schemas**
@scriptCode - optional **In both schemas required**
@scriptOfElement - optional **Missing in both schemas**

**Result**: Addition of @languageofElement and @scriptOfElement needed. Cardinality of @scriptCode needs to be changed?

**Comment by fordmadox** [comment]
Updated.  

Putting in @languageOfElement and @scriptOfElement seems slightly odd, unless descriptiveNote is ever made repeatable, since this element has been made empty aside from the possibility of a single descriptiveNote element.

**Comment by SJagodzinski** [comment]
@fordmadox : But `<p>` withing `<descriptiveNote>` is repeatable and might use different languages. 
I see your point, we will recommend to use //descriptiveNote@languageOfElement to encode the general language used in the child elements and to use //p@languageOfElement to encode a different language. 
On the other hand, to keep the schema simple, we try to avoid the exceptions from general rules to provide lang attributes in all elements that can contain text and in their wrapper elements.

**Comment by karinbredenberg** [comment]
Retested element:
@languageOfElement - optional  **Ok in both schemas**
@scriptCode - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@target - optional **Ok in both schemas**

**Result**: Element ready
